### ISSUE TITLE
Execute from here not working 5.10.1

### ISSUE THREAD

**Issue by chellanihitesh** [katalon-studio/katalon-studio#101]
Run from here or Run from here not working and is disabled. Please help on this.

As in screenshot, 
1. Run step 1 which is a test case to launch application. 
2. Abort execution after step 1.
3. Aim is to run the step 2 on the same open browser in step 1 and step 2.
![image](https://user-images.githubusercontent.com/14137602/52627204-e1598780-2eda-11e9-9a91-6256f8174eb2.png)

**Comment by lieuhuynh1811** [comment]
Please read docs in https://docs.katalon.com/katalon-studio/docs/execute_debug_certain_steps.html#execute-from-a-selected-step,you will find out the solution.
