### ISSUE TITLE
Katalon Studio: Merge Objects to Object Repository

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#103]
https://katalon.zendesk.com/agent/tickets/213

This issue is regarding merging objects to objects repository.

Scenario here is, when we record a test via katalon recorder (record web) Inside a katalon studio and merge the objects to object repository.

we see duplicate objects getting created into the same repository with same name appended with (1) [ex: a_Test Central (1).rs]

Attached screenshots for the same.

Please let us know hoe to resolve the issue?

---

I tried with the latest version of Katalon Studio 5.10.1 and i am able to reproduce the issue.

Also, as discussed on the call, Can you please check with the development team regarding the timelines, when we can get this issue resolved.

**Comment by trongbui** [comment]
We are waiting for the fix.

**Comment by dungleonhart** [comment]
The fix will be released in KS 6.0.5 by this week

**Comment by longngbui** [comment]
Fixed in 6.1.0
