### ISSUE TITLE
Testsuit execuition in katalon and pass fail result will show in TestLink

### ISSUE THREAD

**Issue by nazneen-dapl** [katalon-studio/katalon-studio#108]

**Comment by dungleonhart** [comment]
Dear @nazneen-dapl,

Could you share with us how did you expect the Test Suite and Testlink connection should work and how did you make your try?

Best regard,

**Comment by kalavathijeeru** [comment]
> I have successfully run the testcases in Katalon and result is showing in Testlink pass/fail. But now I wants to connect TestSuits and result must show in Testlink. But its not working. may be future implementation required.

Can you share your Testlink pass/fail with testlink?

**Comment by kalavathijeeru** [comment]
> I have successfully run the testcases in Katalon and result is showing in Testlink pass/fail. But now I wants to connect TestSuits and result must show in Testlink. But its not working. may be future implementation required.

can u share your project pass/fail with testlink?
