### ISSUE TITLE
Unable to record Menu Options in a Page

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#109]
https://katalon.zendesk.com/agent/tickets/128

Hi Katalon team,

We are unable to record Menu Items (in a table) which exists on a page (A page contains multiple Tables as shown in the attached pic).

I am adding HTML Source code for one of the table for which we are unable to record menu options.

**Comment by dungleonhart** [comment]
Does the user agree with the custom keyword approach?
