### ISSUE TITLE
Error occurring while execution of test cases concurrently

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#111]
https://katalon.zendesk.com/agent/tickets/208

We are executing concurrent test cases on Katalon Studio on windows server. On execution of large number of test cases, the test cases are not able to execute completely. And the same test cases which were executing successfully earlier, are failing when executed again.

below is the pattern of the execution observed: 
no. of test cases: 5 pass: 5 fail: 5 
no of test cases: 10 pass:10 fail: 10 
no of test cases: 15 pass:13 fail:2 
no of test cases: 20 pass:4 fail:16

when we executed 20 test cases at once, it gave an error. Please find the complete details in the attached text file.

Same issue occurred after clearing the cache files from the "Temp" folder.

**Comment by trongbui** [comment]
By when can we have an update from the development team? Because our entire project has been stuck as a result of this, and the other requests, and we are unable to move forward. We have to answer to the organisation.

**Comment by dungleonhart** [comment]
This is planned for release 6.0.6 (tentative release date is by March)

**Comment by longngbui** [comment]
This issue is currently in-progress.
