### ISSUE TITLE
Query regarding mailing feature

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#112]
https://katalon.zendesk.com/agent/tickets/231

We are trying to configure the emailing feature of katalon, in order to send reports in mail after the execution of the test cases. We have been trying that for the lotus notes mail server. 
Even after entering all the details, we are unable to configure it.

**Comment by trongbui** [comment]
I request you to get updates from the development team, as this feature is very important for our project and it would be of great help to us. Need this urgently.

**Comment by trongbui** [comment]
https://github.com/katalon-studio/katalon-studio/issues/112

**Comment by Jyotip12** [comment]
Dear Team,
Request you to take this issue on priority.

**Comment by Jyotip12** [comment]
Hi team,
Any updates regarding this?

**Comment by Jyotip12** [comment]
Hi Team,

Please share the updates.
