### ISSUE TITLE
Katalon Studio: Search objects and test cases based on 'Free Text' Search

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#114]
https://katalon.zendesk.com/agent/tickets/232

Please find the details below: 
1. In the Screenshot-1, i have an object "a_ARPAdmin Template" which has a awname "ARPAdminTemplate::TestCategoryLinks:testUnitClick". 
2. When i search with the variable name (a_ARPAdmin Template), i get the search results. But when i search with awname (ARPAdminTemplate::TestCategoryLinks:testUnitClick). Results are not processed.

**Comment by duyluonganh** [comment]
Free Text search only applies for name, descript, tag and not for artifact content.
We will provide `File search` ability to search artifact content

**Comment by duyluonganh** [comment]
Supported in 6.1.2
