### ISSUE TITLE
Full Page Screenshot in the report

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#116]
https://katalon.zendesk.com/agent/tickets/245

How can i take a full page screenshot and append it to the report. Infact will be great if takescreenshot function can be extended to do this

**Comment by Padoplin** [comment]
Hi

Katalon Studio version 7.7+ supports a new keyword to take a full page screenshot. [Learn more](https://docs.katalon.com/katalon-studio/docs/webui-take-fullpage-screenshot.html).

Jass
