### ISSUE TITLE
Running two docker containers

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#118]
https://katalon.zendesk.com/agent/tickets/214

I have used test suite collections and ran the test in a katalon container. I had two test suites in the collection. I was expecting one single html report with results from both the test suites. Instead I found two different folders under report folder(refer to screenshot)

**Comment by manumahendran** [comment]
Hello, Any update on this?

**Comment by Padoplin** [comment]
Test Suite Collection report (in JUnit) is available for Katalon Studio Enterprise user. Please subscribe to use this feature.
