### ISSUE TITLE
Global variables are not sortable and searchable while assigning inside a testcase

### ISSUE THREAD

**Issue by mohan-ally** [katalon-studio/katalon-studio#122]
#### Operating System: (for example: Windows 10 or OSX Sierra)
MAC OSX High Sierra

#### Katalon Studio Version:
5.8.6 (I have moved to the latest version and verified that too, but tests are not running in circle ci if created from 6.0.1)

#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Environment (for Web testing):

Browser and Browser version

#### Environment (for Mobile testing):

* Appium version

* Mobile platform/version under test: (for example: iOS 11 or Android 7)

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)

* Appium Logs: <Project folder>\.appium

* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

Add a variable under default profile
From a test case try to pass that global variable as an argument, the current implementation is not sorted alphabetically nor searchable

#### Expected Behavior:
It should be searchable and sorted

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
https://screencast.com/t/6IZnoSe3V

**Comment by Padoplin** [comment]
Hi there

This feature is available in Katalon Studio 7+. Please upgrade!

Padoplin
