### ISSUE TITLE
Object Spy not working since 5.10.1

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#123]
https://katalon.zendesk.com/agent/tickets/257

Currently testing version 6.0.5, prior to rolling out to our team, but we're finding that the Object Spy is not working. Entering a test URL and starting a Chrome session from within Object Spy is taking us to the correct page, but the Object Spy banner does not appear on the page and no objects can be highlighted or selected. This has been an issue since 5.10.1, but we've been hoping it would be fixed in subsequent releases. Could you advise whether there's any way we could get this working again, please? Many thanks for your help.

Tried uninstalling Chrome and installing Chrome 72, but still had the issue. Also tried Firefox and IE11. Firefox had the issue, but IE installed the ObjectSpyExtension.ObjectSpyBHO plugin and worked.

Unfortunately, we need to test on Chrome primarily, so would really need Object Spy to work on that, and our company prohibits downloading/installing Chrome plugins for security reasons. However, Object Spy was working in previous versions without a plugin, so something seems to have changed since then. Looking at your screenshot, it does seem that you have the plugin installed. Is that what is making the difference?

**Comment by Rubaka** [comment]
any updates on this? as this is a blocker

**Comment by Rubaka** [comment]
Hello, is this blocker still not fixed?
