### ISSUE TITLE
There is no way to get the TestCase Tag information via Katalon Code

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#124]
https://katalon.zendesk.com/agent/tickets/176

There is no way to get the TestCase Tag information via Katalon Code. When i create a test case there is a way to add tags to the test case.

I need to get all the tags via code in one place so that i can categorized my test. There is not way to add this with current Katalon version. 
As per communication in gitter Katalon channel:

Duy Luong @duyluonganh 17:46 
@grathi_gaus_twitter We haven't supported get test case tags yet. You can add an issue on our github site to get support later: https://github.com/katalon-studio/katalon-studio/issues

**Comment by duyluonganh** [comment]
Fixed in 5.3

**Comment by duyluonganh** [comment]
Please use:
```
TestCase testCase = findTestCase(...)
testCase.getTag()
```

**Comment by duyluonganh** [comment]
We are going to support add test case tag information in KS reports in v6.1.2

**Comment by duyluonganh** [comment]
Resolved in v6.1.2
