### ISSUE TITLE
Log Viewer does not show logs to all Test Suites, Show only for first test suite logs.

### ISSUE THREAD

**Issue by ramchandranale** [katalon-studio/katalon-studio#127]
#### Katalon Studio Version: 
Version: 6.0.5
Build: 4

#### Katalon Studio logs: 

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Steps to reproduce:

1. Open Katalon
2. Open Test suite collection
3. Run test suite collection

#### Expected Behavior:

Log Viewer should show logs for all test suite while executing.

#### Actual Behavior:

Log Viewer show log for first test suite only.

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)

![Katalon](https://user-images.githubusercontent.com/30722939/54429484-abf8c180-4746-11e9-9d96-0f7b1b0a081d.png)

**Comment by devalex88** [comment]
Please see my answer for a similar question https://forum.katalon.com/t/test-suite-collection-isnt-running-all-test-suites-for-api-tests/21328/5.

**Comment by raghupola-vg** [comment]
Is there an option to set the log viewer to current execution?
For me, i just see the 1st test execution and then i have to change manually to the desired test suite to see which one is executing at the moment.
