### ISSUE TITLE
Could not retrieve the log of a test suite executed in a test suite collection

### ISSUE THREAD

**Issue by dungleonhart** [katalon-studio/katalon-studio#13]
Issue code: KAT-3595
Original post: https://forum.katalon.com/discussion/9273/could-not-retrieve-the-log-of-a-test-suite-executed-in-a-test-suite-collection

**Comment by jchatronLetsignit** [comment]
It would be a blast to have this fixed !

**Comment by dungleonhart** [comment]
This issue has been fixed in Katalon Studio 5.9
