### ISSUE TITLE
Throws Exception while capturing the Mobile Object

### ISSUE THREAD

**Issue by azfar27** [katalon-studio/katalon-studio#130]
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log\
https://drive.google.com/open?id=1fnWlPl4Y83X5rU09KLlSMTipGDllA_Dw

#### Environment for : Mobile Testing

* Appium version: v1.12.0

* Mobile platform/version under test: Android 5.1.1

* Real device: OPPO A37fw

* Appium Logs: <Project folder>\.appium
https://drive.google.com/open?id=1r0jccJf5HPTad0kXPrVPep0KrROojywR

* Application file: not possible

#### Steps to reproduce:

After creating the Mobile Project, When I click on Mobile Object Spy or Mobile Recorder and set the Application apk Path and then press the start button, It will launch the application on Mobile but throws the exception as well Unable to capture objects Reason: ExecutionException

Details: java.lang.NullPointerException

#### Screenshots:
https://drive.google.com/open?id=1r3hsO3TyMNShyx_LJyPk4n8uJOsblO9f
![Katalon](https://user-images.githubusercontent.com/47141123/54742246-b1408b00-4be2-11e9-8443-28a5c51bbebe.PNG)

**Comment by duyluonganh** [comment]
Hi @azfar27, please try with appium v1.8.1. We are currently official support this version on Windows.

**Comment by azfar27** [comment]
It's working with appium v1.8.1 thanks
