### ISSUE TITLE
install_parse_failed_no_certificates | LinekedIn Jobs professional apk | Android Device version 9

### ISSUE THREAD

**Issue by SusanAnna** [katalon-studio/katalon-studio#131]
After installing Katalon , the mobile recorded throws the following error and doesn't install  the app. However if the app is already installed manually  , then the process opens the app in device view. Can this be checked please

@ screenshots attached below. After clicking on OK of the first button , the next popup shows up
![Error popup](https://user-images.githubusercontent.com/38496265/55053870-9c04aa00-5083-11e9-92b3-a7dfc3dc22a6.png)
![Next Popup after clicking the OK button of first popup](https://user-images.githubusercontent.com/38496265/55053871-9c9d4080-5083-11e9-9a90-7e0ae6590374.png)

**Comment by SusanAnna** [comment]
LinkedIn Jobs professional profile networking_v4.1.236_apkpure.com - apk for linkedIn

**Comment by duyluonganh** [comment]
@SusanAnna please attach your apk file

**Comment by devalex88** [comment]
Close due to inactivity.
