### ISSUE TITLE
Error - Bad Port : 0 is displayed randomly

### ISSUE THREAD

**Issue by tonythomas28** [katalon-studio/katalon-studio#132]
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

No Log file in the above said path only an xml file names "workingsets.xml"

#### Steps to reproduce:

Randomly getting Bad Port : 0 while executing the test suit. And this error comes as soon as i click on the Run Button

#### Expected Behavior:

No Error should be displayed

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
![Screenshot 2019-03-29 at 12 48 00 PM](https://user-images.githubusercontent.com/21123857/55216401-a610df00-5222-11e9-9d3b-5fbacb1d8c81.png)

**Comment by MorggieL** [comment]
I see this as well but I'm not sure what causes this - it seems to be random.

**Comment by devalex88** [comment]
Thank you all for the report. This issue has been resolved in Katalon Studio 6.3.0.rc7 https://github.com/katalon-studio/katalon-studio/releases/tag/v6.3.0.rc7.
