### ISSUE TITLE
Katalon stops executing after switching to webview

### ISSUE THREAD

**Issue by iSravyaS** [katalon-studio/katalon-studio#133]
I am writing test cases for the Hybrid application. I am trying to switch to webview in order to perform some actions on webview related elements. But the test case stops executing once it is switched to webview . It throws no error and just stops executing.

I have tried both the ways one using katalon keywords and other using appium method. Nothing works.

Method1: Using Katalon Keyword
AndroidDriver driver = MobileDriverFactory.getDriver()

Mobile.delay(5)

Mobile.switchToWebView(FailureHandling.STOP_ON_FAILURE)

Method2: Using appium
AndroidDriver driver = MobileDriverFactory.getDriver()

Mobile.delay(5)

Set contextNames = driver.getContextHandles();
for (String contextName : contextNames) {
System.out.println(contextName)
}

driver.context(contextNames.toArray()[1]);

myText = driver.findElement(By.xpath("//*[@id = ‘front’]/child::div"))

If anyone has already faced this problem, It would be of great help if given a solution.

Thanks,

Sravya

**Comment by duyluonganh** [comment]
Hi @iSravyaS,

Please show your execution log

**Comment by devalex88** [comment]
Close due to inactivity.

**Comment by swaranbm** [comment]
Were you able to figure this out please? I am facing the same problem in katalon.

**Comment by daptanque** [comment]
Same when I try to interact with the input fields I'm not able to set text in them... Any idea how to overcome such?
