### ISSUE TITLE
Katalon SOAP SendRequest - No option to pass proxy details through the script

### ISSUE THREAD

**Issue by musthi** [katalon-studio/katalon-studio#136]
Katalon SOAP SendRequest - No option to pass proxy details through the script.

In a common Katalon Project, I have Web Automation which will work fine with no proxy in the Katalon Studio Preferences. And secondly I have SOAP calls within the same katalon project which works only if the manual proxy is set in the Katalon Studio Preferences (Server, IP).

So I am trying to find a solution to pass proxy details programatically within the script for the SOAP SendRequest calls (WS.SendRequest), but there is no solution found until now. It is being one month I am trying all the sources available.

Please add this feature. I am eagerly awaiting for your support on this. Until now this tool is beautiful except for this feature.

**Feature Needed:** An option to pass proxy details programatically via the script for the SOAP/API SendRequest calls

**Comment by musthi** [comment]
Please feedback

**Comment by Padoplin** [comment]
Hi @musthi,

Thank you for your contribution. We already put it in our Product Backlog of Katalon Studio version 6.4.0. Stay tuned!

Regards,

Linh

**Comment by devalex88** [comment]
Please see https://docs.katalon.com/katalon-studio/docs/proxy-preferences.html#pass-proxy-details-through-the-script.
