### ISSUE TITLE
Unable to click on Object using Chrome Headless

### ISSUE THREAD

**Issue by ctilos** [katalon-studio/katalon-studio#137]
#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 7 and Windows 10
#### Katalon Studio Version:
Katalon Studio VersionL 6.1.0
#### Katalon Studio logs:
[.log](https://github.com/katalon-studio/katalon-studio/files/3087614/default.log)

#### Environment (for Web testing):

Chrome, Firefox , Chrome (Headless) and Firefox (Headless)

#### Environment (for Mobile testing):
None
* Appium version
None
* Mobile platform/version under test: (for example: iOS 11 or Android 7)
None
* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)
None
* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)
None
* Appium Logs: <Project folder>\.appium
None
* Application file (.apk/.ipa): (if possible)
None
#### Steps to reproduce:

We encountered Unable to click on object "Add"upon running it in the Chrome (Headless),  its working in Chrome, Firefox and Firefox (Headless).

Please see below the Object I tried to clicked:

<a _ngcontent-lah-c6="" class="btn btn-with-icon header-button-size" href="#/leads" style=""><fa-icon _ngcontent-lah-c6="" class="text-success ng-fa-icon" ng-reflect-icon-prop="fas,plus-circle" style=""><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="plus-circle" class="svg-inline--fa fa-plus-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm144 276c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92h-92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z" style=""></path></svg></fa-icon><span _ngcontent-lah-c6="" class="filter-icon" translate="" ng-reflect-translate="" style="">Add</span></a>

![image](https://user-images.githubusercontent.com/49701241/56255936-4f981180-60f9-11e9-80c5-9d7252a456da.png)

I tried different setting like XPath , Attribute and CSS but it still not working.
![image](https://user-images.githubusercontent.com/49701241/56255828-dac4d780-60f8-11e9-9a75-4bd8457b4922.png)

![image](https://user-images.githubusercontent.com/49701241/56255913-3d1dd800-60f9-11e9-9a7e-4ffb78d7114c.png)

Please help me how can I able to click the said element in the Katalon Studio for Chrome (Headless)

**Comment by duyluonganh** [comment]
Hi @ctilos,

Could you share us full the execution log from **Console Log** tab. Please copy them and attach to a log file.

**Comment by ctilos** [comment]
Hi Duyluonganh,

I already fixed the problem, the solution I make it run in the chrome headless is to:

1.) Add Set View Port Size   --> 1920;1080 
   > to set the maximum size of the browser used in the chrome headless
2.) Added a Delay , 5 secs
3.) Get Url --> to  check if the current URL
4.) Focus  the 'a' Tag Button
5.) Added a Delay, 5 secs
6.) Now add click to that 'a' Tag Button 
7.) then run and its now able to click on Object 

![image](https://user-images.githubusercontent.com/49701241/56487837-1bfd2300-650f-11e9-97e7-6fd0db54e1d7.png)
