### ISSUE TITLE
Get test case failure message from testCaseContext

### ISSUE THREAD

**Issue by dungleonhart** [katalon-studio/katalon-studio#14]
Issue code: KAT-3677
Originally posted at https://forum.katalon.com/discussion/4566 by Dharmesh Verma

**Comment by dungleonhart** [comment]
The failure message and stack trace are available in textCaseContext since Katalon Studio 5.9

**Comment by senf-f** [comment]
How exactly can I get the failure message?
_textCaseContext_ is not listed on [api-docs.katalon.com](https://api-docs.katalon.com/index.html).
