### ISSUE TITLE
Why hasn't the email been sent successfully from the command line 

### ISSUE THREAD

**Issue by hcuih** [katalon-studio/katalon-studio#141]
🚨 The issue tracker is not for questions 🚨
My script is as follows：
./Katalon\ Studio.app/Contents/MacOS/katalon --args -noSplash  -runMode=console -consoleLog -projectPath="/Users/xxxx/workspace/xxxx/wg.prj" -sendMail="xxxxx@xxxxx.com" -retry=0 -testSuitePath="Test Suites/Login/Login" -executionProfile="stg(private)" -browserType="Chrome (headless)"
When I ran it, sending the mail never succeeded, but there was no error
![2211556586432_ pic_hd](https://user-images.githubusercontent.com/46768744/56936037-a2c18980-6b27-11e9-80e7-5fe36f4aa43e.jpg)

**Comment by devalex88** [comment]
Did you config your mail server in Katalon Studio? By the way, this kind of questions should be asked in our forum.
