### ISSUE TITLE
Web UI Project : Deleted Local variables are still referenced in TestCase

### ISSUE THREAD

**Issue by musanas** [katalon-studio/katalon-studio#146]
#### Katalon Studio Version: 6.1.3 , Build: 3

It is observed that the deleted local variables are still referenced in the test case, leading to test failure with groovy.lang.MissingPropertyException: 

This is true in the case of a renamed variable as well

Steps to reproduce:
1. Assume there is a testcase
2. There is a local variable for this test case
3. The testcase script uses this local variable and pass the value of it during execution
4. Delete / rename the local variable
5. Observe the test case
6. The variable is being still referenced leading to test case failure
7. The deletion / renaming of local variable migh have either happened intentionally/accidently. Its worth giving a notification to the user on such action. Or remove the variable at places where it being referenced
8. Otherwise this will lead to lot of confusion especially when it happen to larger automation projects.

**Comment by Padoplin** [comment]
Hi @musanas 

Please provide your test script for further investigation. Thanks!
