### ISSUE TITLE
Migrating Java Selenium + TestNg framework to Katalone

### ISSUE THREAD

**Issue by musanas** [katalon-studio/katalon-studio#147]
Hi
Currently in our compnay, we do have a relatively very large Web UI automation project built with plan Java Selenium Web driver + TestNg
The framework is something we ourselves designed and built it over the time to meet our purpose.

Recently we have been exploring Katalone studio for the web ui projects and have been looking for ways to migrate the existing projects in to Katalone
I haven't found any reasonably flexible way to migrate the project to Katalone, i understand this has a lot to do with in and out of our framework anyway.

But I would like to check is there any plan to have a feature in Katalon studio to help migrate plain java + testNg projects to Katalone

Regards
Musaffir

**Comment by devalex88** [comment]
Unfortunately, we don't have any plan for this feature at this moment.
