### ISSUE TITLE
Can't specify user name in Git login dialogs

### ISSUE THREAD

**Issue by davidmw** [katalon-studio/katalon-studio#149]
#### Steps to reproduce:

If I use the Git Clone option in the UI, I'm shown a window with URL, username and password fields. My repo is on Azure DevOps so the URL starts like: https://my-company@dev.azure.com

Adding this URL causes the username field to auto populate with 'my-company' but I need to put my personal authentication details in. On this screen it is possible to edit the default user name, which I do and I also select the option to save the credentials.

However on other Git options like 'Push' the URL is prepopulated and readonly. The username field also can't be edited and is again set to 'my-company.'  So at this point it seems that I can clone a repo but I can't push to it since I can't specify the correct username.

**Comment by EnlightonOcean** [comment]
Here is your solution.
repleace https://my-company@dev.azure.com with https://<alias name your created >@dev.azure.com and issue is resolved.
