### ISSUE TITLE
Configure Email Server Settings via console parameters

### ISSUE THREAD

**Issue by dinbtechit** [katalon-studio/katalon-studio#150]
Setting Email settings in every single project is tedious it would be great if there was an option to configure mail server settings via console parameters.

```
-emailServer="mymailserver.com"  -emailPort="25" -emailUser="username" -emailPassword="password"  -emailReplyToAddress="NO-REPLY-Katalon@example.com"  -emailSubjectLine="Project A Regression Test Summary - ${STATUS}"
```
| parameter   |   value                        |
|--------------|-------------------------|
| emailServer  | "mymailserver.com" |
| emailPort |  "25"
| emailUser | "username" | 
| emailPassword | "password" |
| emailReplyToAddress | "NO-REPLY-Katalon@example.com" | 
| emailSubjectLine | "Project A Regression Test Summary - ${STATUS}" |

**Comment by dinbtechit** [comment]
Uh oh. Any reason why this was closed?

**Comment by Padoplin** [comment]
Hi

I have escalated this request to our development team to consider for implementation. I will let you know when there's an update.
