### ISSUE TITLE
Support Dark Theme

### ISSUE THREAD

**Issue by duyluonganh** [katalon-studio/katalon-studio#158]
KS will support two themes:
- Light theme (current theme as default)
- Dark theme
User can switch between to these two themes.

**Comment by HarryCIPHR** [comment]
When this releases the forum will go crazy ;)

**Comment by duyluonganh** [comment]
It will available in a beta release soon.

Thanks for your attention.

**Comment by francorebu** [comment]
Please @duyluonganh dark theme
