### ISSUE TITLE
"Continue Recording" a Test Case deletes Web Service parameters

### ISSUE THREAD

**Issue by crayfishuk** [katalon-studio/katalon-studio#159]
#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 10 

#### Katalon Studio Version:
6.1.5 build 3

#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log
[katalon.log](https://github.com/katalon-studio/katalon-studio/files/3212329/katalon.log)

#### Environment (for Web testing):

Chrome Version 74.0.3729.169 (probably not relevant)

#### Environment (for Mobile testing):

Not applicable

#### Steps to reproduce:

* Create a new Web project
* Create a new WebServiceRequest in the Object Repository (e.g. 'jsonplaceholder request')
  * Define a variable in the WSR Object and give it a default value (e.g. '1').
![image](https://user-images.githubusercontent.com/2369502/58256818-9667cf80-7d67-11e9-8224-9c9ee5c2742d.png)

* Create a new TestCase (e.g. 'New Test Case') and record some Web UI actions
![image](https://user-images.githubusercontent.com/2369502/58257243-797fcc00-7d68-11e9-94a7-57facedc9ade.png)

* Add a 'Web Service Keyword to the TestCase' - a 'Send Request' call to the WebServiceRequest created above and **set a different value for the variable**
![image](https://user-images.githubusercontent.com/2369502/58257469-e2ffda80-7d68-11e9-92de-8c52664564f4.png)

* Check that Script now includes variable for WS.sendRequest
```
WebUI.openBrowser('')
WebUI.navigateToUrl('https://jsonplaceholder.typicode.com/')
WebUI.verifyElementText(findTestObject('Object Repository/h2_Example'), 'Example')
WS.sendRequest(findTestObject('jsonplaceholder request', [('number') : '15']))
WebUI.closeBrowser()
```
* Save all files
* Click _Record Web_ and select 'Yes I do' to continue recording.
* Run any selected lines in the UI test to open a browser, and record a new click on an item.
![image](https://user-images.githubusercontent.com/2369502/58257840-894be000-7d69-11e9-867c-99cf5275166c.png)

* Click OK and save any new resources
* Check Script - Variables for WS.sendRequest have been deleted.
```
WebUI.openBrowser('')
WebUI.navigateToUrl('https://jsonplaceholder.typicode.com/')
WebUI.verifyElementText(findTestObject('Object Repository/h2_Example'), 'Example')
WS.sendRequest(findTestObject('Object Repository/jsonplaceholder request'))
WebUI.closeBrowser()
WebUI.click(findTestObject('Object Repository/h2_Resources'))
```
* Confirm that variable value has been lost in _Manual_ tab
![image](https://user-images.githubusercontent.com/2369502/58258056-ee9fd100-7d69-11e9-8f7b-492d8310540a.png)

#### Expected Behavior:

Recording additional items into an existing Test Case MUST NOT corrupt any existing lines in the test case.

#### Actual Behavior:

Any WebServiceRequests that call WS.sendRequest, WS.sendRequestAndVerify, and possibly others, will lose any variable definitions. No error or warning is displayed, and because the variables are only displayed when you double-click on the WSR Object name, it's an invisible deletion.
```
WS.sendRequest(findTestObject('Object Repository/jsonplaceholder request', [('number') : '15']))
```
has become
```
WS.sendRequest(findTestObject('Object Repository/jsonplaceholder request'))
```

This happens for multiple variables - all are removed.

**Comment by duyluonganh** [comment]
Hi @crayfishuk,

Please double-check this issue on the latest version v6.3.3.

Thanks
