### ISSUE TITLE
Case detection on file rename

### ISSUE THREAD

**Issue by alexzahn** [katalon-studio/katalon-studio#165]
Renaming a file in Katalon Studio fails if you are only updating the capitalization. For example, you cannot change the name of a file `keyword.groovy` to `Keyword.groovy` as it states that a file already exists with that name.

#### Operating System: (for example: Windows 10 or OSX Sierra)
MacOS 10.14.5

#### Katalon Studio Version:
6.1.5

#### Katalon Studio logs:
N/A

#### Steps to reproduce:
1. In Katalon Studio create a file or custom keyword with an all lowercase name
2. Attempt to change only the casing of the name of the file

#### Expected Behavior:
File name changes

#### Actual Behavior:
Error detection on already existing file due to case insensitivity in uniqueness detection

**Comment by GrzegorzPi** [comment]
confirm for:
Windows 10
Katalon Stidio 6.1.5

OK button on rename confirmation became disabled when we change only capitalization for:
- test case name
- object repository name
- object repository catalog name

**i.e.**
```
old name: Name
new name: naMe
```

**Comment by duyluonganh** [comment]
@huynguyen2908 Please follow this issue

**Comment by Padoplin** [comment]
Please upgrade to Katalon version 7.0.0.
