### ISSUE TITLE
Unable to recognize ios(12.2) device in Katalon studio(6.2) 

### ISSUE THREAD

**Issue by Bhagi4597** [katalon-studio/katalon-studio#166]
Hi Team, 

I have done Katalon setup for IOS, below are my configurations:
MAC OS :10.14.5
Katalon : 6.2.0
Xcode : 10.2.1
Appium :1.12.1
Testing mobile app on IOS 12.2

Below are issues:
1. Real device not recognized

is this known issue ? or anyone facing this issue?

**Comment by devalex88** [comment]
Hi @Bhagi4597,

Sorry for the inconvenience. However, this issue list is for tracking bugs and feature requests. Please ask the question at https://forum.katalon.com - there will be more help on troubleshooting your setup.

**Comment by Bhagi4597** [comment]
@devalex88  Apologies. Closing this.
