### ISSUE TITLE
faultCode=OTHER_ERROR: An error occurred trying to resolve schema referenced at

### ISSUE THREAD

**Issue by patriciasimonep** [katalon-studio/katalon-studio#168]
**Hello,** 
I am working on soap calls using katalon, i cant seem to make a successful call, it says **"com.kms.katalon.core.webservice.exception.WebServiceException: javax.wsdl.WSDLException: WSDLException (at /wsdl:definitions/wsdl:types/xs:schema[2]): faultCode=OTHER_ERROR: An error occurred trying to resolve schema referenced at 'dc8e07f2-7916-11e8-b2c8-cdeeaf50761b?xsd=xsd0'.: java.io.FileNotFoundException: This file was not found: "** looks like i cant access the schema or xsd location but it works fine with soap ui.

**Operating System:** Windows 10 64bit

**Katalon Studio Version:** 64-6.2.1

**Log folder attached** 

**Steps to reproduce:**

Create soap request with header parameters and basic authentication

 **Expected Behavior:** Should be able to get successful request

 **Actual Behavior:** Unable to send request

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
[.log](https://github.com/katalon-studio/katalon-studio/files/3339032/default.log)
<img width="304" alt="katalon soap error" src="https://user-images.githubusercontent.com/42575440/60340307-743b2000-99ab-11e9-8a8e-dd298cefc2f4.PNG">

**Comment by duyluonganh** [comment]
@patriciasimonep Can you provide us the WSDL endpoint or the Soap Request file?

**Comment by patriciasimonep** [comment]
it seems to be looking for the xsd in the local drive instead of the endpointURL, can you give some ideas what are the possible issues here ?

**Comment by patriciasimonep** [comment]
without proxy: REST is working and SOAP is encountering the error i reported,
with proxy: both REST and soap are encountering 502 error
what else are the possible issues im encountering with SOAP when i send request? can you list all down the possible issues?

**Comment by patriciasimonep** [comment]
i am able to send soap request from v6.3.0.rc5 thank you
