### ISSUE TITLE
API Response Pretty Body displays nothing

### ISSUE THREAD

**Issue by evy0311** [katalon-studio/katalon-studio#178]
#### Operating System:
Ubuntu 19.04

#### Katalon Studio Version:
6.3.0

#### Katalon Studio logs:
None

#### Steps to reproduce:
Open Katalon Studio and create a new API Project. Create an API call that returns data in any of the response formats (json, xml, html). Make a call to any API and open the response window on the right hand side. Click on `pretty` or `raw`. No data is display unless `preview` is selected.

#### Expected Behavior:
The response should show formatted data under the `pretty` and `raw` tabs.

#### Actual Behavior:
Nothing is display but a blank, white section when clicking on `pretty` and `raw`. The only view that works is the `preview` tab.

#### Screenshots / Videos: 
Link to two screenshots on Imgur: https://imgur.com/gallery/vBsEelI

#### Others having the same issue: 
https://forum.katalon.com/t/pretty-response-not-working/12640

**Comment by AmrutaDravid** [comment]
hi i am using Katalon Studio Enterprise version 7.2.1 i am not able to see any respose for my api request in the pretty body. I can only view it in preview tab

**Comment by Padoplin** [comment]
Hi folks

Please create a new ticket with a bug report template. There's not enough information for our team to investigate.

Thanks

Jass
