### ISSUE TITLE
Proxy configuration needs exclusion list

### ISSUE THREAD

**Issue by ffmit** [katalon-studio/katalon-studio#179]
The typical enterprise has a local intranet with lots of applications installed,
which are accessible **without** proxy. 

But Katalon Studio needs to load information from internet, so it needs to have
the proxy configured, as seen under "Window" -> "Katalon Studio Preferences" -> "

My wish is, to add an exclusion list, so that the tools can be used better in companies with proxy restrictions.

Please see below:

![image](https://user-images.githubusercontent.com/18364436/62197314-eb375000-b37f-11e9-8a35-1499592c94f4.png)

**Comment by ysubramaniamgosi** [comment]
@Katalon Team - Do we have any ETA for fixing this?

**Comment by Padoplin** [comment]
Hi there!

Thank you for your suggestion. We have already added the exclusion list in Proxy configuration to our Product Backlog. 

Regards,

Linh.

**Comment by asoltesz** [comment]
@Padoplin :

Hi, Is there an ETA for fixing this?

**Comment by ysubramaniamgosi** [comment]
@Padoplin & katalon Team

We are seeing the proxy option - "Use system proxy configuration" is not working and it behaves as like option "No proxy". Please suggest us why it is not working and help us resolving this. It is blocking automation of our total project critically.

![image](https://user-images.githubusercontent.com/53518721/63646708-b9679e00-c71f-11e9-9584-c1c0a7e7a658.png)

**Comment by kazurayam** [comment]
+1 for supporting the exclusion list

**Comment by staniere** [comment]
me too
+1 for supporting the exclusion list !

**Comment by daleqq** [comment]
+1, this feature is vital after I upgraded to 7.0. I need to set proxy to activate each time I open the katalon, but need to remove it when I run the test, otherwise it always display DNS problem.

**Comment by Bredda** [comment]
+1
Not being able to configure properly the proxy exclusion list makes using 7.0 behind a corporate proxy an absolute nightmare du to constant activation check and auto shutdown when activation failed

**Comment by staniere** [comment]
Hello, 
for information, this lack was annoying for me on version 6.3 as I was not able to use Katalon plugin nor sending results to Analytics, but it katalon was still usable.  
But since version 7.0, it just prevent me from using it as (like daleqq), I have to configure proxy at each Katalon startup and deactivate it just after startup in order to be able to launch my tests on my company network. 
So for the moment, I continue to use Katalon 6.3.3

@Padoplin @Katalon, do you plan this exclusion list soon ?
I think that every big companies have a proxy and a lot of them won't be able to use Katalon 7 without it.

**Comment by Padoplin** [comment]
Hello everyone

Proxy exception list will be released soon in the upcoming versions. Meanwhile, stay tuned!

Jass

**Comment by daleqq** [comment]
For my case:
> +1, this feature is vital after I upgraded to 7.0. I need to set proxy to activate each time I open the katalon, but need to remove it when I run the test, otherwise it always display DNS problem.

After upgrade to v7.2.1, the following solution is still useless in my case.
> The ability to exclude proxy is available in version 7.2 and later. Katalon Studio only supports proxy exceptions in web recorder and spying with Chrome and Firefox.

**Comment by Bredda** [comment]
Same here.
Proxy exceptions when running a Katalon test case is really essential in an enterprise contexte.
