### ISSUE TITLE
Add custom header by script or pre request script?

### ISSUE THREAD

**Issue by ishara** [katalon-studio/katalon-studio#181]
What even types available in plugin API for pre-request request modifications ?

Example usage - Modify header parameter before send request, using script.

**Comment by huynguyen2908** [comment]
@ishara,
Do you want the pre-request script to be executed when sending request in your test script only? Or you want it to also work when sending request via request object view?
If you choose the first option, we will consider creating a new test listener type for achieving your desired behavior. Please refer to https://docs.katalon.com/katalon-studio/docs/test-listeners-test-hooks.html#manage-test-listeners for more information.
