### ISSUE TITLE
Problem with renaming to upper/lower case with the same name

### ISSUE THREAD

**Issue by adrenalineWest** [katalon-studio/katalon-studio#189]
When trying to rename a folder to Upper/lower case characters with the same name the "Already Exist" shown.

For example, Rename "sample-folder" to "Sample-Folder"

- Operating System:  Windows 10

- Katalon Studio Version: 6.3.2

**Comment by duyluonganh** [comment]
Hi @adrenalineWest 

This issue will be fixed in v7.0.0 release.

Thanks for your report
