### ISSUE TITLE
Try Catch with Katalon keyword does not work

### ISSUE THREAD

**Issue by kimiin** [katalon-studio/katalon-studio#191]
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

#### Environment (for Web testing): Chrome 76

Browser and Browser version

#### Steps to reproduce:

1. Set global failure handling is "CONTINUE ON FAILURE or OPTIONAL"
2. Use try-catch in LoginPage class like below:

> @Keyword
> 	static def clickToForgotYourPassword(){
> 		
> 		try{ //failed step
> 			WebUI.click(findTestObject("test/LoginPage/lnk_ForgotYourPasswords"))
> 		}catch(StepErrorException|StepFailedException e){
> 			Loggers.setFailureHandling("Cannot click to Forgot Your Password link", FailureHandling.STOP_ON_FAILURE)
> 		}catch(Exception e){
> 			Loggers.setFailureHandling(e.getMessage(), FailureHandling.STOP_ON_FAILURE)
> 		}finally{
> 			Loggers.clickToMessage("Click to Forgor Your Password link")
> 		}
> 	}

4. Back to test case and call it:

> LoginPage.clickToForgotYourPassword()

#### Expected Behavior:
My exception in "catch block" must be executed, and the test case must be stopped
#### Actual Behavior:
WebUI.click exception is executed, and it continues on failure

**Comment by duyluonganh** [comment]
Hi @kimiin 

Please update Katalon Studio to the latest version v6.3.3.

Thanks

**Comment by kimiin** [comment]
thanks, no need, just restart the katalon, haiz
