### ISSUE TITLE
Bring back the Reports in Tests Explorer because its very difficult to track report right now

### ISSUE THREAD

**Issue by dennisdg07** [katalon-studio/katalon-studio#192]
We're having difficulties tracking our reports in Test Suite, much better if you bring it back it Test Explorer, please

Also, when highlighting a specific error in the reports, it keeps coming back in the start(upper portion of the logs) when I start highlighting the text.

Bring back Reports in Tests Explorer

**Comment by duyluonganh** [comment]
Fixed in 7.0.0 for Enterprise users
