### ISSUE TITLE
passing proxy information to the selenium grid to connect to application behind firewall

### ISSUE THREAD

**Issue by SriharshaTV** [katalon-studio/katalon-studio#20]
Hi Katalon team, 
We are currently trying to use Katalon with Selenium Grid to connect to an application behind the firewall. Currently it's not supported to send the proxy information to remote browser. In one of the forum it was told that it's expected in  Q3-2018 , but didn't see any versions showing that it's fixed. 
are there any plans to support this ?
is there any workaround so that until it get supported we can use it.

Thanks,
Sriharsha.

**Comment by jyotimittal01** [comment]
Hello, Is there an update on this?

**Comment by devalex88** [comment]
Please test again with [Katalon Studio 6.0.6 beta](https://forum.katalon.com/t/updated-mar-8th-beta-release-6-0-6/20561) and let us know the result.
