### ISSUE TITLE
Unable to delete copied object repository file(Test Object)

### ISSUE THREAD

**Issue by dennisdg07** [katalon-studio/katalon-studio#200]
I have successfully copied a Test Object file from one folder to another but when I was trying to delete it, there's a loading bar and is successfully loaded but file is still in the folder and not deleted.

Operating System: Windows 10

Katalon Studio Version: 6.3.3

**Comment by duyluonganh** [comment]
@dennisdg07 
Can you share us the object.rs file?

**Comment by dennisdg07** [comment]
Hi @duyluonganh ,
Kindly see attached file, I changed the file extension name from .rs to .txt so I could attach the file.

[label_Thank you Payment has been.txt](https://github.com/katalon-studio/katalon-studio/files/3681840/label_Thank.you.Payment.has.been.txt)

**Comment by dennisdg07** [comment]
Additional info.

This is not happening only on copied file, I can't delete the other objects, after clicking Yes in the Delete pop-up, this progress bar will show but will just vanish instantly and when I checked the object the I'm trying to delete, it's still there and not deleted.
![image](https://user-images.githubusercontent.com/51792705/66058205-89a48500-e56c-11e9-804d-c4e492264ef3.png)
