### ISSUE TITLE
Email port use always 25

### ISSUE THREAD

**Issue by giansalex** [katalon-studio/katalon-studio#201]
**Operating System**: Windows 10
**Katalon Studio Version**: 7.0.0

#### Expected Behavior:
Connect smtp using port `3535`

#### Actual Behavior:
Connect smtp using port `25`

![image](https://user-images.githubusercontent.com/14926587/65729201-1047f680-e083-11e9-831a-af4cebfa8c65.png)

**Comment by Padoplin** [comment]
Hi everyone

We've just released Katalon Studio version 7.3.0 that includes this bug fix. Please read our [release notes](https://docs.katalon.com/katalon-studio/new/version-70.html) for more information and upgrade.

Happy Testing

Jass
