### ISSUE TITLE
Unable to install Katalon app on Mac

### ISSUE THREAD

**Issue by wenxiaoy** [katalon-studio/katalon-studio#202]
#### Operating System: 
macOS Mojave, version 10.14.5

#### Katalon Studio Version:
6.3.3

#### Katalon Studio logs:

* MacOS logs folder: !SESSION 2019-10-04 10:48:04.143 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_NZ
Framework arguments:  -keyring /Users/**/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault -keyring /Users/**/.eclipse_keyring

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.308
!MESSAGE Could not install bundle plugins/net.sf.supercsv.super-csv_2.1.0.jar   A bundle is already installed with the name "net.sf.supercsv.super-csv" and version "2.1.0"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.309
!MESSAGE Could not install bundle plugins/org.eclipse.equinox.simpleconfigurator.manipulator_2.0.200.v20160504-1450.jar   A bundle is already installed with the name "org.eclipse.equinox.simpleconfigurator.manipulator" and version "2.0.200.v20160504-1450"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.311
!MESSAGE Could not install bundle plugins/com.kms.katalon.selenium-standalone_1.0.0.201908270734.jar   A bundle is already installed with the name "com.kms.katalon.selenium-standalone" and version "1.0.0.201908270734"
<e/209435165_macosx_cocoa_x86_64/configuration/1570139284342.log" 1060L, 93847C
!SESSION 2019-10-04 10:48:04.143 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_NZ
Framework arguments:  -keyring /Users/**/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault -keyringg
 /Users/**/.eclipse_keyring

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.308
!MESSAGE Could not install bundle plugins/net.sf.supercsv.super-csv_2.1.0.jar   A buu
ndle is already installed with the name "net.sf.supercsv.super-csv" and version "2.11
.0"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.309
!MESSAGE Could not install bundle plugins/org.eclipse.equinox.simpleconfigurator.mann
ipulator_2.0.200.v20160504-1450.jar   A bundle is already installed with the name "oo
rg.eclipse.equinox.simpleconfigurator.manipulator" and version "2.0.200.v20160504-144
50"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.311
!MESSAGE Could not install bundle plugins/com.kms.katalon.selenium-standalone_1.0.0..
201908270734.jar   A bundle is already installed with the name "com.kms.katalon.selee
nium-standalone" and version "1.0.0.201908270734"
!SESSION 2019-10-04 10:48:04.143 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_NZ
Framework arguments:  -keyring /Users/**/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault -keyring /Users/**/.eclipse_keyring

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.308
!MESSAGE Could not install bundle plugins/net.sf.supercsv.super-csv_2.1.0.jar   A bundle is already installed with the name "net.sf.supercsv.super-csv" and version "2.1.0"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.309
!MESSAGE Could not install bundle plugins/org.eclipse.equinox.simpleconfigurator.manipulator_2.0.200.v20160504-1450.jar   A bundle is already installed with the name "org.eclipse.equinox.simpleconfigurator.manipulator" and version "2.0.200.v20160504-1450"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.311
!MESSAGE Could not install bundle plugins/com.kms.katalon.selenium-standalone_1.0.0.201908270734.jar   A bundle is already installed with the name "com.kms.katalon.selenium-standalone" and version "1.0.0.201908270734"

!ENTRY org.eclipse.update.configurator 4 0 2019-10-04 10:48:06.312
!MESSAGE Could not install bundle plugins/slf4j.api_1.7.25.jar   A bundle is already installed with the name "slf4j.api" and version "1.7.25"

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
<img width="442" alt="Screen Shot 2019-10-04 at 11 32 03 AM" src="https://user-images.githubusercontent.com/4599800/66168800-c79fc700-e69a-11e9-9730-7fa168aa4a07.png">

**Comment by duyluonganh** [comment]
@wenxiaoy Please move the Katalon Studio.app to **Applications** folder

**Comment by wenxiaoy** [comment]
Thanks @duyluonganh

**Comment by skydenicoloda** [comment]
not solved for me
