### ISSUE TITLE
[Linux] 6.3.3 Test case fails with "LinkageError" on test cases with custom XPath test objects

### ISSUE THREAD

**Issue by PoisonousJohn** [katalon-studio/katalon-studio#203]
#### Operating System: (for example: Windows 10 or OSX Sierra)

ArchLinux

#### Katalon Studio logs:

[log.txt](https://github.com/katalon-studio/katalon-studio/files/3691539/log.txt)

#### Environment (for Mobile testing):

* Appium version
➜ appium --version
1.14.1

* Mobile platform/version under test: Android 7

* Real device or emulator/simulator: Real device Xiaomi Mi 4c

* Appium Logs: <Project folder>\.appium
[appium.log](https://github.com/katalon-studio/katalon-studio/files/3691550/appium.log)
* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

Use Mobile.tap on any test object with custom XPath

#### Expected Behavior:
Test step complets with success

#### Actual Behavior:
I get this error on any test object with xpath
https://gist.github.com/PoisonousJohn/822619ba4d1508fc03c5ded19cb9eec7
#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)

![output](https://user-images.githubusercontent.com/1488281/66226043-92b76280-e6e2-11e9-8944-e58678185c1b.gif)

P.S. Doesn't reproduce on 6.2.2. Stumbled on this after update

**Comment by duyluonganh** [comment]
@PoisonousJohn Please try again with a fresh download

**Comment by PoisonousJohn** [comment]
Doesn't reproduce on newer versions
