### ISSUE TITLE
KS7 asks for online activation for every time the KS7 application is launched

### ISSUE THREAD

**Issue by gouthamsam** [katalon-studio/katalon-studio#209]
For each and every time the KS7 application is launched, it prompts the user for online activation. It's strange

**Comment by Padoplin** [comment]
Hello @gouthamsam 

Katalon Studio 7.0.0 requires a network connection to connect to Katalon Server for every time you online activate. Make sure you have a network connection and configure proxy properly.

When you have successfully activated Katalon Studio, the app automatically saves your credentials for the next session.

You're recommended to upgrade to the latest version of Katalon Studio.

Jass
