### ISSUE TITLE
Unable to edit a gobal variable name

### ISSUE THREAD

**Issue by mohan-ally** [katalon-studio/katalon-studio#21]
Add a global variable and edit the variable name

Was able to edit the variable value and not the name via studio 

https://screencast.com/t/M4CIa8uG

**Comment by dungleonhart** [comment]
Dear @mohanraj-chronus,
Sorry for the super late response. It seems that we have reproduced the issue on MacOS and planned to fix it. Just wondering if you are a MAC user or not?

**Comment by mohanraj-chronus** [comment]
Yes I am running Katalon on Mac

**Comment by mohanraj-chronus** [comment]
Yes. I am using mac

**Comment by kms-loantran** [comment]
Hello @mohanraj-chronus,
A new bug submitted for the development team on your issue. Thank you for your report.
In the meanwhile, you can hit Enter key instead of clicking OK button for a work-around.

Thank you.

**Comment by dungleonhart** [comment]
Issue code: KAT-3914
