### ISSUE TITLE
Add ability to export/import project settings & preferences

### ISSUE THREAD

**Issue by FrenchMasta** [katalon-studio/katalon-studio#210]
### Ability to export/import project settings & preferences

When upgrading Katalon Studio I have to reconfigure my preferences

- Appearance

- IDE Settings (Intellisense, formatting, etc.)

Add option to export preferences & settings and add option to import these settings

**Comment by Padoplin** [comment]
Hi @FrenchMasta 

You can reuse your project settings and preferences by moving the `setting` folder containing those configurations from one project to another.

For example, go to  **<project_folder>\settings\internal >** copy and paste `com.kms.katalon.execution.properties`  in another project to reuse only the execution settings.

Hope it helps!

Jass

**Comment by FrenchMasta** [comment]
Thank you very much
