### ISSUE TITLE
Katalon fails to launch for 7.06 RC2

### ISSUE THREAD

**Issue by pabz616** [katalon-studio/katalon-studio#214]
Been a long-time advocate for Katalon and have used it extensively on projects in the past. New computer, new Katalon version, suddenly seeing new issue where none existed before:

#### Operating System: 
MacBook Air - OS 10.15 (Catalina)

#### Katalon Studio Version: 
7.06 RC2 (latest)

#### Katalon Studio logs: 
N/A

#### MacOS logs folder: 
N/A

#### Steps to reproduce:
1. Visit Katalon.com
2. Click download for Mac

#### Expected Behavior:
Follow steps shown at https://docs.katalon.com/katalon-studio/docs/getting-started.html#for-macos

#### Actual Behavior:
Never make it to the step requiring activation due to a pop-up error (shown below)

#### Screenshots / Videos: (please see attach screenshots)
![Screen Shot 2019-11-01 at 11 17 01 AM](https://user-images.githubusercontent.com/22268013/68038572-a5509780-fca0-11e9-927b-b63b2d2a1abc.png)

#### Log File:
[1572621371332.log](https://github.com/katalon-studio/katalon-studio/files/3798670/1572621371332.log)

#### Note to Devs:
* Attempted to install Eclipse thinking that was an issue, but no remedy found
* Attempted to update JRE, but I received an error not relevant to this issue

**Comment by pabz616** [comment]
Please reply to vergara.pablo0616@gmail.com when this is resolved.
-thx

**Comment by duyluonganh** [comment]
@pabz616 Please put the Katalon Studio app file to the **Applications** folder.

Thanks

**Comment by pabz616** [comment]
@duyluonganh - woo hoo! All set! Looking forward to re-acquainting myself with the framework and the latest updates :) 

Thanks
