### ISSUE TITLE
Katalon Studio should support jBehave eclipse plugin to improve readiness and easy of use for jBehave tests

### ISSUE THREAD

**Issue by devalex88** [katalon-studio/katalon-studio#230]
Copied from katalon-studio-samples/jbehave-plugin-sample#1.

Hi,

Katalon Studio should consider including [jBehave Eclipse plugin](https://jbehave.org/eclipse-integration.html) in order to improve usability of KS for writing jBehave tests.

This plugin is something similar to what KS already does for Cucumber.

Please consider adding this support since as of now jBehave tests are supported but working with them is hard and developers will not be happy to switch to KS in that enviornment. Adding Eclipse plugin should not be relatively simple since Katalon Studio is already built on the top of Eclipse.

Thanks,
Rasko

**Comment by rpjesivac** [comment]
Hi @devalex88 ,

Any updates regarding timeline for adding jbehave eclipse plugin into Katalon Studio?
This should not be a major effort on your side, and will improve jBehave usability for the end users.

Thanks,
Rasko
