### ISSUE TITLE
Access to Katalon Recorder

### ISSUE THREAD

**Issue by Airdevelopments** [katalon-studio/katalon-studio#231]
This is a feature request.

How likely is it, that you will add plugin access to the Katalon Recorder in Katalon Studio to customize the recording behavior for example?

**Comment by devalex88** [comment]
You can install Katalon Recorder extension on your browsers and use "Record with active browsers" mode - see https://docs.katalon.com/katalon-studio/docs/record-web-utility.html.

To customize the behavior, please clone https://github.com/katalon-studio/katalon-recorder, modify, and replace the official Katalon Recorder with the in-house extension.
