### ISSUE TITLE
Process/Tests hanging at the end while constructing email.

### ISSUE THREAD

**Issue by Ghaar** [katalon-studio/katalon-studio#233]
We regularly (1-5 times a week) have a test which when it gets to the end of it's execution starts to build the email report and never completes.

`System is unable to email report. Reason: net.sf.jasperreports.engine.JRRuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded`

I am using the tagged 6.1.5 docker image from: https://hub.docker.com/r/katalonstudio/katalon/tags/
following the instructions from https://github.com/katalon-studio/docker-images

This is being executed via our Jenkins instance, which has a lot of RAM (20+ GB) and hard drive space (100+ GB) free. 

A coworker identified the Thread causing the trouble:
`java.awt.font.LineBreakMeasurer.nextLayout() `
it eventually runs out of memory. This is a thread dump from visual VM.

![image](https://user-images.githubusercontent.com/15033628/60194451-5df45f00-9807-11e9-81c3-d5f0e3e0ad1a.png)

Additionally by default the JVM is set in such a way that the max heap to 2GiB
without cracking open the docker image and directly editing the katalon.ini is there a way to increase that value via a --config flag or some other method?

**Comment by Padoplin** [comment]
Hi @Ghaar

Please upgrade to Katalon Studio 7.2.4+ for this enhancement. [Read more](https://docs.katalon.com/katalon-studio/docs/execution-settings.html#allow-editing-jvm-parameters-in-execution-settings).

Padoplin
