### ISSUE TITLE
"Problems" button typo in Error dialog box.

### ISSUE THREAD

**Issue by mdoerr-qa** [katalon-studio/katalon-studio#234]
![image](https://user-images.githubusercontent.com/58863368/70829079-9a118100-1da1-11ea-87da-7dde8caca223.png)

"Show **Prolems** in View"

**Comment by Padoplin** [comment]
Hi

We've just released Katalon Studio version 7.3.0 that includes this bug fix. Please read our [release notes](https://docs.katalon.com/katalon-studio/new/version-70.html) for more information and upgrade.

Happy Testing

Jass
