### ISSUE TITLE
SendKeys Keys.ENTER on Firefox add extra characters

### ISSUE THREAD

**Issue by devalex88** [katalon-studio/katalon-studio#243]
Copied from kms-technology/katalon#3602.

https://forum.katalon.com/t/keys-chord-keys-enter-adds-extra-character-in-firefox/27173
https://forum.katalon.com/t/webui-sendkeys-should-accept-an-org-openqa-selenium-keys-argument/27991
https://forum.katalon.com/t/how-to-press-enter-with-webui/10950

**Comment by afiorey** [comment]
Is there a specific reason that this bug was closed without being resolved? I've seen quite a few forum posts about this (3 above) and most link back to this as the resolution, but it was never fixed.
