### ISSUE TITLE
Adding more than 50 test case in a Test Suite hangs the application

### ISSUE THREAD

**Issue by PrabodhGhosh** [katalon-studio/katalon-studio#25]
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Environment (for Web testing):

Browser and Browser version : NA

#### Environment (for Mobile testing):

* Appium version : NA

* Mobile platform/version under test: (for example: iOS 11 or Android 7)

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)

* Appium Logs: <Project folder>\.appium

* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

Please include an SSCCE (Short, Self Contained, Correct [compilable] example) description http://sscce.org/

1. We have 500 + test cases. 
2. We are trying to add all the test cases in a suite. 

#### Actual Behavior: Katalon studio hangs and does not respond. We need to wait for hours. 

It was earlier raised here : 

https://forum.katalon.com/discussion/9929/katalon-studio-hangs-for-indefinite-time-while-trying-to-add-500-test-cases#latest 
![test suite issue](https://user-images.githubusercontent.com/28348577/49284779-9de6a400-f4bb-11e8-864c-70ef1337e242.png)

**Comment by devalex88** [comment]
Thank you @PrabodhGhosh,

We've made some performance improvements recently. Could you please verify if that solves the issue?

**Comment by Padoplin** [comment]
Hello everyone

In Katalon Studio version 7.1, when a bulk number of Test Cases are added to a Test Suite, there will be a progress dialog displayed.

Please upgrade when the new version is available. Read more about the [release note](https://docs.katalon.com/katalon-studio/new/version-71.html#new-features).

Jass
