### ISSUE TITLE
Check and uncheck test folders were more than 50 test cases causes hanging the application

### ISSUE THREAD

**Issue by devalex88** [katalon-studio/katalon-studio#251]
Copied from kms-technology/katalon#4057.

#### Steps
* Open the test project
* Open **New Test Suite**
* **Check** and  **uncheck** test folders have more than 50 test cases 
#### Result
- Expected: KS doesn't hang and the user can check and uncheck test folders.
- Actual result: KS hangs and the user can't check and uncheck test folders.

**Comment by russgthomas** [comment]
My suite has 99 Test Cases.

Platform Katalon 7.1.2, Win7.

Can't reproduce.
