### ISSUE TITLE
Tests are now false-passing with a broken step

### ISSUE THREAD

**Issue by thanhto-katalon** [katalon-studio/katalon-studio#258]
https://forum.katalon.com/t/tests-are-now-false-passing-with-a-broken-step/36545

#### Katalon Studio Version: 
* 7.x
#### Steps:
* I migrated my test project from earlier versions to 7.x
* I have a Test Case which should fail because the element being clicked on is not visible.

#### Expected Behavior:
* The test should also fail on 7.x

#### Actual Behavior:
* The test (falsely) passes in 7.x, although subsequent steps fail because the element is not being actually clicked.

#### Relevant log on earlier version:

12-04-2019 10:07:19 AM - [FAILED] - Test Cases/QA Finished Test Cases/SID-5689 (ED1995) Virtual Terminal - Capture FAILED because (of) (Stack trace: com.kms.katalon.core.exception.StepFailedException: Unable to click on object ‘Object Repository/ED - 1995/Page_Capture Adjust Payment/button_Select All’ (Root cause: org.openqa.selenium.ElementNotVisibleException: element not interactable
(Session info: chrome=78.0.3904.108)
(Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: ‘3.7.1’, revision: ‘8a0099a’, time: ‘2017-11-06T21:07:36.161Z’
System info: host: ‘GET-LAP-DEV005’, ip: ‘172.16.193.5’, os.name: ‘Windows 10’, os.arch: ‘amd64’, os.version: ‘10.0’, java.version: ‘1.8.0_181’
Driver info: com.kms.katalon.selenium.driver.CChromeDriver

#### Relevant log on 7.x

2019-12-04 10:41:12.043 ERROR c.k.k.c.w.keyword.builtin.ClickKeyword - :x: javascript error: Cannot read property ‘left’ of undefined
(Session info: chrome=78.0.3904.108)
Build info: version: ‘3.141.59’, revision: ‘e82be7d358’, time: ‘2018-11-14T08:25:53’
System info: host: ‘GET-DSK-DEV010’, ip: ‘172.16.193.3’, os.name: ‘Windows 10’, os.arch: ‘amd64’, os.version: ‘10.0’, java.version: ‘1.8.0_181’
Driver info: com.kms.katalon.selenium.driver.CChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 78.0.3904.108, chrome: {chromedriverVersion: 77.0.3865.40 (f484704e052e0…, userDataDir: C:\Users\RSCHWA~1.GET\AppDa…}, goog:chromeOptions: {debuggerAddress: localhost:52372}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}

#### Investigation

https://groups.google.com/forum/#!topic/selenium-users/E6DBLXrxOPM
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3044

**Comment by Padoplin** [comment]
This bug is fixed in Katalon Studio version 7.2.5.
