### ISSUE TITLE
Support hierarchical groupings in Keywords Browser

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#267]
### Forum
https://forum.katalon.com/t/organization-of-custom-keywords-within-the-keywords-browser/23320/7

### Feature
Keywords Browser should support nested hierarchical grouping of keywords. Currently all keywords appear in one folders.
![](https://forum.katalon.com/uploads/default/original/2X/5/5aaa5cfd1dd61dc4b3410e7e007ce3724b297346.png)

**Comment by Padoplin** [comment]
In version 7.5.5+, you can organize Custom Keywords in an alphabetical order in Keyword Browser and categorize them with keywordObject.
