### ISSUE TITLE
Comments not getting published in the log

### ISSUE THREAD

**Issue by Mowogman** [katalon-studio/katalon-studio#27]
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Environment (for Web testing):

Browser and Browser version

#### Environment (for Mobile testing):

* Appium version

* Mobile platform/version under test: (for example: iOS 11 or Android 7)

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)

* Appium Logs: <Project folder>\.appium

* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

Please include an SSCCE (Short, Self Contained, Correct [compilable] example) description http://sscce.org/

If it’s not possible to provide the web page link (for web), please consider creating a reproducible page on https://jsfiddle.net/

Please also provide your test scripts if possible.

**Comment by Mowogman** [comment]
Check the forum for details

https://forum.katalon.com/discussion/11874/webui-comment-no-longer-printing-the-comment-to-the-log#latest

**Comment by dungleonhart** [comment]
It has been fixed in 5.10.1
