### ISSUE TITLE
Window Object references in Test Case do not change when Window Objects are re-named

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#289]
### Forum issue
https://forum.katalon.com/t/katalon-7-2-1-windows-application-object-renaming-issue/40642

**Comment by rapidroamer** [comment]
I also observe this issue when restructuring the object repository.
Example: If I create sub folders in the object repository and move objects around, their references does not get updated in test cases (able to observe from code view).

Sometimes, the reference gets updated by without "/Object Repository" in the reference path  (able to observe from code view).

**Comment by Padoplin** [comment]
Hi everyone

This bug has been fixed in version 7.4.2 which is available for download [here](https://github.com/katalon-studio/katalon-studio/releases/v7.4.2).

Jass
