### ISSUE TITLE
PDF report is not getting generated

### ISSUE THREAD

**Issue by PrabodhGhosh** [katalon-studio/katalon-studio#29]
#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 10

#### Katalon Studio Version:
5.9.1

#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

Warning: NLS missing message: COMMAND_NAME_OPEN in: com.kms.katalon.composer.components.impl.constants.composerComponentsImplMessages
Warning: NLS unused message: Key in: com.kms.katalon.composer.search.constants.composerSearchMessages

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Environment (for Web testing):

Browser and Browser version - Chrome 

Version 70.0.3538.110 (Official Build) (64-bit)

#### Environment (for Mobile testing):

* Appium version

* Mobile platform/version under test: (for example: iOS 11 or Android 7)

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)

* Appium Logs: <Project folder>\.appium

* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

Please include an SSCCE (Short, Self Contained, Correct [compilable] example) description http://sscce.org/

I have a simple suite of 6 test cases. Once the suite is executed, I am trying to export the report in PDF format, which is not completing at all and running endlessly. I have to close Katalon Studion from Windows Task Manager to end this process. 

Please see the second error message. 

Please also provide your test scripts if possible.

#### Expected Behavior:

The report should be generated with seconds. 

#### Actual Behavior:

PDF report is not getting generated. 
![image](https://user-images.githubusercontent.com/28348577/49634711-8cede380-fa23-11e8-9aab-c6447679092c.png)

**Comment by PrabodhGhosh** [comment]
![image](https://user-images.githubusercontent.com/28348577/49641028-0cd07980-fa35-11e8-9863-3828f20138ee.png)

**Comment by vinhpnguyen** [comment]
@PrabodhGhosh : Please share with us the complete report folder on your local machine. You can archive it in .zip format and attach it here.

**Comment by PrabodhGhosh** [comment]
@vinhpnguyen Please find the attached zip file. If anything else is required, please let me know. 
[New folder.zip](https://github.com/katalon-studio/katalon-studio/files/2670568/New.folder.zip)

**Comment by PrabodhGhosh** [comment]
@vinhpnguyen  Please find attached zip file. 
[New folder.zip](https://github.com/katalon-studio/katalon-studio/files/2670571/New.folder.zip)

**Comment by vinhpnguyen** [comment]
> @vinhpnguyen Please find attached zip file.
> [New folder.zip](https://github.com/katalon-studio/katalon-studio/files/2670571/New.folder.zip)

Thanks for your file. We will investigate it and inform you soon.

Regards

**Comment by dinbtechit** [comment]
PDF reports are not getting generating. Using the latest version of Katalon 6.2.2 and have Basic Report Plugin installed. PLEASE HELP!

**Comment by devalex88** [comment]
@PrabodhGhosh This issue has been resolved.

@dinbtechit Please ask your question in https://forum.katalon.com with a detailed description.

**Comment by AkshadaShetty** [comment]
PDF reports are not getting generated.I am using 6.3.1 version and cannot see the pdf generated.
Please can anyone resolve this issue please
