### ISSUE TITLE
Spelling error on "Error" popup

### ISSUE THREAD

**Issue by evy0311** [katalon-studio/katalon-studio#296]
#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 10
#### Katalon Studio Version:
7.6.2 Build 1
#### Katalon Studio logs:
[log.log](https://github.com/katalon-studio/katalon-studio/files/4307457/log.log)
#### Environment (for Web testing):
N/A (this has no effect on the issue)
#### Environment (for Mobile testing):
N/A (this has no effect on the issue)
#### Steps to reproduce:
Open Katalon Studio. Create a project and create a keyword (.groovy file) with an error. The specific error I've received is an "unable to resolve class" error. Create a test case. Now click the Run button. In the error popup, the button (far left) says "Show Prolems in View" should say "Problems" instead. 
#### Expected Behavior:
Button text should read "Show Problems in View"
#### Actual Behavior:
Button text reads "Show Prolems in View" (missing a b in problems)
#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
![Katalon bug report Problems misspelled](https://user-images.githubusercontent.com/33989929/76228944-d6fde000-61f7-11ea-9d7c-0cfed083a30b.PNG)

**Comment by duyluonganh** [comment]
Duplicates with: https://github.com/katalon-studio/katalon-studio/issues/234
