### ISSUE TITLE
The dialog message needs to be updated

### ISSUE THREAD

**Issue by linhhuynhtruc** [katalon-studio/katalon-studio#297]
#### Katalon Studio Version: 7.0.10

Please update the message and format in the below dialog.

<img width="1430" alt="Screen Shot 2020-03-11 at 10 24 58 AM" src="https://user-images.githubusercontent.com/44353766/76379540-ee1d0900-6382-11ea-8320-6687e051cdc5.png">

**Comment by duyluonganh** [comment]
Fixed in v7.2.0
