### ISSUE TITLE
Remove the lastRun property in Test Suite to avoid Git conflicts

### ISSUE THREAD

**Issue by devalex88** [katalon-studio/katalon-studio#30]
https://forum.katalon.com/t/suggestion-katalon-studio-last-run-info-could-be-saved-in-a-separate-fille-not-in-the-ts-file/11291

https://forum.katalon.com/t/why-changes-of-lastrun-info-in-a-ts-file-conflict-how-to-prevent-it/14872

https://forum.katalon.com/t/git-master-master-rejected-non-fast-forward/14531

**Comment by jchatronLetsignit** [comment]
^this 👍

**Comment by dungleonhart** [comment]
It has been fixed in 5.10.
