### ISSUE TITLE
error al integrar en jenkins

### ISSUE THREAD

**Issue by maximilianofni** [katalon-studio/katalon-studio#301]
en todas las versiones que instalo katalon studio no puedo integrar con jenkins ???
![2020-03-12_16-05-29](https://user-images.githubusercontent.com/17895688/76558201-a1692900-647b-11ea-8bb6-513382be4bc0.png)

**Comment by duyluonganh** [comment]
@maximilianofni Please use English to discuss here.
Where do you put your offline license?

**Comment by maximilianofni** [comment]
I can't get the license.
how is it done
I use katalon studio for windows. help me if you know?

**Comment by Padoplin** [comment]
Hello

First, you need to subscribe to an annual and node-locked license to activate it offline. See [How to subscribe to a Katalon license](https://docs.katalon.com/katalon-studio/docs/license-subscription.html). If you have already subscribed, please create a ticket in Zendesk for support service.
