### ISSUE TITLE
Only a partial list of the test case variables are available in the test suite data binding dialog.

### ISSUE THREAD

**Issue by veerjd** [katalon-studio/katalon-studio#306]
#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 10

#### Katalon Studio Version:
7.2.6

#### Katalon Studio logs:
N/A

#### Environment (for Web testing):
Firefox 74.0 (64bit)

#### Steps to reproduce:
See screenshots for discrepancy

#### Expected Behavior:
See all variables from the test case

#### Actual Behavior:
See only a partial list

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
![image](https://user-images.githubusercontent.com/26885867/77674585-35e68780-6f62-11ea-9892-177f4aaf306d.png)
![image](https://user-images.githubusercontent.com/26885867/77674606-3e3ec280-6f62-11ea-954e-191047138698.png)

**Comment by Padoplin** [comment]
Hi @veerjd 

Could you please provide detailed steps for reproducing the issue? Thanks.

Padoplin

**Comment by veerjd** [comment]
@Padoplin you can close this. No way I can remember how, but I'm pretty sure I only just opened the two without doing any extra steps
