### ISSUE TITLE
Plugin removed each time, I start Katalon application

### ISSUE THREAD

**Issue by hkaddour** [katalon-studio/katalon-studio#310]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://forum.katalon.com/categories/katalon-analytics.
Hello,

We have bought 4 licences for our team. But when I try to install a plugin, we ask each user to buy a licence. But I have already bought a licence.
Also I've install plugin by by using the zip package, but when I start Katalon application, I lost my plugin.

Could you tell me how to install plugin because it's free for me?
Thanks.
Hichème Kaddour
Tel: 0628234308

**Comment by minhthanh3145** [comment]
@hkaddour 

Please refer to this answer: 
https://forum.katalon.com/t/i-have-a-licence-kse-and-cant-install-plugin/41671/2

**Note** that should must extract the zip file into Jar files and place them under appropriate folder structure
