### ISSUE TITLE
Request `Verify Element` feature for Mobile

### ISSUE THREAD

**Issue by thongnmtran** [katalon-studio/katalon-studio#320]
The request is from Katalon forum:
https://forum.katalon.com/t/mobile-mobile-spy-is-not-validating-xpath/42607/3?u=thongnmtran

> "I realize that Mobile Spy is only for capturing elements but assumed that if I added my own object to the Spy it might validate it - will be a very useful feature when released :slight_smile:"
> &nbsp;&nbsp; \- **Dan_Bown**

**Comment by Padoplin** [comment]
Hello everyone

This enhancement is available in version 7.8+. 

Jass
