### ISSUE TITLE
[Katalon BDD] Content of Feature file in KS after imported from Jira is not incorrect

### ISSUE THREAD

**Issue by kms-loantran** [katalon-studio/katalon-studio#324]
Steps:
- Create a task/bug on Jira cloud with Katalon BDD custom field as following:
<img width="961" alt="Screen Shot 2020-04-29 at 9 31 12 AM" src="https://user-images.githubusercontent.com/29113513/80558209-bab23e80-8a03-11ea-8e68-4eb3567aebf8.png">
- Set up Jira integration to KS
- Import the issue to KS

Expected result: The content of the feature file should be the same as Katlaon BDD custom field value of the jira issue
Actual reslut: The content of the feature file is not the same

<img width="1327" alt="Screen Shot 2020-04-29 at 9 31 36 AM" src="https://user-images.githubusercontent.com/29113513/80558278-0533bb00-8a04-11ea-9b4d-2510fb5abfe9.png">

Source: https://forum.katalon.com/t/integration-of-jira-with-katalon-for-using-cucumber-bdd/26937/10

**Comment by Padoplin** [comment]
This bug is fixed in version 7.6.5.
