### ISSUE TITLE
[Katalon BDD] Scenario Reporter to ReportPortal

### ISSUE THREAD

**Issue by luc007** [katalon-studio/katalon-studio#328]
1. Install ReportPortal
    https://reportportal.io/installation  

2. Install Plugins as below:
![image](https://user-images.githubusercontent.com/1424225/81511248-03140b00-92e6-11ea-9198-04301d9e93c9.png)

3. Create a feature file as Katalon BDD  
![image](https://user-images.githubusercontent.com/1424225/81511201-8ed96780-92e5-11ea-8e8c-00c5dc5e2b7e.png)

4. In Test Case create a Cucumber Runner with plugin as below:
 import org.junit.runner.RunWith;
    import cucumber.api.CucumberOptions;
    import cucumber.api.junit.Cucumber;
    @RunWith(Cucumber.class)
    @CucumberOptions(features="Your_Folder_Path", glue="", plugin = ["pretty",
                        "com.epam.reportportal.cucumber.ScenarioReporter"])
    public class MyCucumberRunner {
    }
 
Error:
Test Cases/Web UI/Testing/MyCucumberRunner FAILED.
Reason:
com.kms.katalon.core.exception.StepFailedException: These following reason:
 [Couldn't load plugin class: com.epam.reportportal.cucumber.ScenarioReporter. It does not implement cucumber.api.Plugin]

**Comment by duyluonganh** [comment]
@luc007 
Please move your .jar files to **Drivers** folder
