### ISSUE TITLE
Dark theme looks messy on Windows 10

### ISSUE THREAD

**Issue by cosflaviu** [katalon-studio/katalon-studio#330]
#### Steps to reproduce:
1. Switch to dark theme
2. Observe the buttons and overall look and feel

#### Expected Behavior:
Dark theme is correctly displayed.

#### Actual Behavior:
Visually unappealing, some buttons have artifacts, some color choices are weird.

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
![LoREgLXwb6](https://user-images.githubusercontent.com/11185284/81658658-a463a400-9441-11ea-8c95-64dee10e062f.png)

Notes: It looks totally different to what I can see in the screenshots from the product presentation: https://www.katalon.com/katalon-studio/

**Comment by Padoplin** [comment]
Hello @cosflaviu 

In v7.9, the IDE look and feel is substantially improved with extending Dark theme support in additional Windows areas, including the text of radio buttons, check-box, and group control.

Please check out[ this new release](https://docs.katalon.com/katalon-studio/new/what-is-new-79.html#multiple-enhancements-enabled-by-eclipse-platform-upgrade) and upgrade. 

Jass
