### ISSUE TITLE
Katalon support Appium Remote

### ISSUE THREAD

**Issue by jlane9** [katalon-studio/katalon-studio#34]
Under "Project Settings" -> "Execution" -> "Default", Katalon supports the following:

**Web UI**
- Chrome
- Firefox
- IE
- Safari
- Edge
- Remote (Browserstack, etc.)
- Chrome (Headless)
- Firefox (Headless)

**Mobile**
- Android
- iOS

What is missing is that Katalon does not support "Remote" on the mobile side, which is preventing us from testing applications with Browserstack. On the web side it supports switching the server type of Remote from Selenium to Appium, but that does not appear to work testing native applications, only web applications running a browser in an iOS or Android environment.

**Comment by mlspinylobster** [comment]
I also need it.

I just got succeeded to execute Android test via remote Appium server.
It's an only Android example but it may be helpful for you: https://github.com/mlspinylobster/help-me-katalon-forum-10239

I wish Katalon to support the use cases like this.

**Comment by NgocTMPhan** [comment]
Please tell us which scenario you want to achieve and your used steps. We will see if Katalon Studio does support it or is there something missing from your side.

**Comment by mlspinylobster** [comment]
@NgocTMPhan 
I want to use remote Android devices through [OpenSTF](https://github.com/openstf/stf).

To use it, I have to exec such commands before the testing:
```
export ADBHOST="<Device IP>"
export ANDROID_ADB_SERVER_PORT="<Device Port>"
adb tcpip "<Device Port>"
adb connect "<Device IP>:<DevicePort>"
```

However Appium restarts adb server by default. So I can't use Android execution mode.
I have to launch my own Appium server which I can control and use it from Katalon Studio.

Thank you

**Comment by duyluonganh** [comment]
The author resolved the problem https://forum.katalon.com/t/unable-to-execute-via-remote/13797
