### ISSUE TITLE
[Web Recorder] Unable to 'run from here' when record web with IE Web Driver version 3.6.0.0 

### ISSUE THREAD

**Issue by luondinh** [katalon-studio/katalon-studio#341]
Step to Reproduce  :
![image](https://user-images.githubusercontent.com/62001984/83222126-bb282b80-a1a1-11ea-9487-d1829117df5b.png)
1. Record web with IE Browser

- Start browser with URL 'https://login.globalglaze.in/'
- Set text for UserID field as '1479'
- Set text for Password field as 'KatalonStudio'
- Click Login button

2. Using run from here

- Click on Step two (Set text for UserID field as '1479' in above)
- Right click and run from here
The issue occur in there are:
- [x] Cannot set text for  UserID field, Password Field
- [x] Cannot click the Login button
ROOT CAUSE: the driver cannot find correctly the captured element 

Resolve:
- Update IE Web Driver to version 3.150.0.0 and retry above steps
![image](https://user-images.githubusercontent.com/62001984/83226757-e5cbb180-a1ac-11ea-9177-1a5b54defc62.png)

**Comment by Padoplin** [comment]
This bug is fixed in version 7.6.5.
