### ISSUE TITLE
[Web Recorder] Not capture navigate action when starting record on IE

### ISSUE THREAD

**Issue by luondinh** [katalon-studio/katalon-studio#342]
- Step to reproduce:

1. Open Katalon Studio and start recorder
2. Choose IE as the starting browser and start (make sure URL not plank)
3. The browser will be started annd navigated to target URL, but the action navigate not be captured by the recorder.

![image](https://user-images.githubusercontent.com/62001984/83398970-94c8f100-a42a-11ea-9fb4-9ebad6fc3f13.png)

- Root cause: 

> The Katalon Recorder Addon Socket starting after the IE Web Driver started. So it cannnot capture navigate action (execute when starting IE Web Driver)

- Suggestion to resolve this issue:

Add navigate action to the step  tree view when starting record if the browser is IE

**Comment by Padoplin** [comment]
This bug is fixed in version 7.6.5.
