### ISSUE TITLE
Support scrolling Test Explorer to the direction of the mouse

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#344]
https://forum.katalon.com/t/katalon-studio-test-explorer-broken-scroll/44442

**Problem**

Users try to drag and drop Test Object from one folder to another in a big project with many folders. Test Explorer does not scroll to the direction of the mouse when drag-and-drop.

**Comment by Padoplin** [comment]
Please use cut and paste instead.
