### ISSUE TITLE
Please tag alpha, beta and rc releases as Pre-release

### ISSUE THREAD

**Issue by mrowell** [katalon-studio/katalon-studio#347]
Could you please consitently tag alpha, beta and rc releases in https://github.com/katalon-studio/katalon-studio/releases as Pre-releases so we can easily indentify production releases for deployments. 

Thanks,
Marcus

**Comment by Padoplin** [comment]
Hey @mrowell 

Thanks for your suggestion. I just added a pre-release tag to version 8.0.0 alpha. Sorry for any inconvenience this may have caused.

Padoplin
