### ISSUE TITLE
Katalon does not function on HiDPI

### ISSUE THREAD

**Issue by kusinara** [katalon-studio/katalon-studio#349]
#### Operating System: (for example: Windows 10 or OSX Sierra)

5.7.4-artix1-1

#### Katalon Studio Version:

64-7.5.10 (Tested also on previous versions)

#### Katalon Studio logs:

[.log](https://github.com/katalon-studio/katalon-studio/files/4810444/default.log)

#### Steps to reproduce:

1. Start Katalon

#### Expected Behavior:

Katalon opens and prompts login/registration, can create and open a project

#### Actual Behavior:

Katalon opens without a login/registration prompt (or with 'Operation in progress...' window),
creating a project results in an 'Unable to create project.' message (however the project folder is still populated afterwards), opening a project hangs on 'Operation in progress' (same as when opening Katalon, see screenshot)

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)

![2020-06-22-011308_3840x2160_scrot](https://user-images.githubusercontent.com/67153278/85237295-0bec1680-b426-11ea-87fa-ddca56bb4a73.png)

#### Notes
Katalon works as expected while using 1920x1080 on the same machine and display, works even if DPI is set incorrectly.

**Comment by Padoplin** [comment]
Hi @kusinara 

Please try opening your project on [Katalon Studio version 8.0.0alpha](https://github.com/katalon-studio/katalon-studio/releases/tag/v8.0.0.alpha) and see if you still encounter the issue.

Padoplin

**Comment by kusinara** [comment]
@Padoplin 
It seems like the issue is fixed on version 8.0.0 alpha, although this version does not correctly scale GTK, this can be done manually with GDK_SCALE=2 and GDK_DPI_SCALE=0.5.

Glad this was taken care of.
