### ISSUE TITLE
Feature request - Wants to create a webhook to run from Katalon studio to up size or down size Azure vm’s

### ISSUE THREAD

**Issue by shivam23shah** [katalon-studio/katalon-studio#358]
I have all my automation test running on Azure VM’s. When I run any suites I will up size the vm’s & once it’s done I down size them. I have Azure run books to do that for me. Is there any way I can create a webhook & run from Katalon studio to up size or down size the vm’s?
How can I run webhook from Katalon or
How can I Automate this process via Katalon studio? I want to run Powershell runbook scripts from Katalon studio to upscale or downscale Azure vm’s. Is this something can I do it in Katalon at the moment?

One of the Katalon developer suggest me to open up feature request in Github and request to add in Katalon future release.

**Comment by duyluonganh** [comment]
Hi @shivam23shah,

For your specific case, you should create a Katalon platform plugin that hooks to the test suite finished event. Please refer to Slack plugin as a sample: https://github.com/katalon-studio/katalon-studio-slack-plugin/blob/master/src/main/java/com/katalon/plugin/slack/SlackEventListenerInitializer.java

Tutorial to create and debug plugins: https://docs.katalon.com/katalon-store/docs/publisher/create-plugin.html
https://forum.katalon.com/t/tutorial-debug-your-platform-plugin-using-eclipse-ide/23500
