### ISSUE TITLE
Katalon Studio 5.9.1 auto-generated import statements are missing "import org.openqa.selenium.Keys as Keys"

### ISSUE THREAD

**Issue by barda999** [katalon-studio/katalon-studio#36]
And it results to following exception initially:
groovy.lang.MissingPropertyException: No such property: Keys 
https://forum.katalon.com/t/stack-trace-error-any-ideas-new-to-katalon-studio-recorder/13505/3

**Comment by dungleonhart** [comment]
Dear @barda999 ,
Does the answer in the forum work for you?
https://forum.katalon.com/t/stack-trace-error-any-ideas-new-to-katalon-studio-recorder/13505/4

**Comment by dungleonhart** [comment]
Dear @barda999,
It seems the issue happens when test cases are manually created then appending with recorded test steps. We acknowledge that this is an issue and will fix it in our next release.
Best regards,

**Comment by barda999** [comment]
thanks

**Comment by devalex88** [comment]
This issue has been fixed.
