### ISSUE TITLE
Cannot move Test Objects between folders when one Test Object is broken

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#364]
## Steps to reproduce
- Modified any Test Object's physical file so that it isn't a valid XML. 
- Move another Test Object into a different folder.

## Expected behavior
The Test Object that isn't broken can be moved.

## Actual behavior
No Test Object can be moved.

![image](https://user-images.githubusercontent.com/16775806/88504107-df678380-cffd-11ea-8d38-d026d77deeb6.png)

**Comment by Padoplin** [comment]
Hi there!
This bug was fixed in v8.1.0. Pls upgrade!
Jass
