### ISSUE TITLE
Support executing Windows tests and Web tests together

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#368]
Users want to use Desktop Testing capabilities to handle pop-ups when downloading a file in Web test cases. It would be nice if Katalon supports running Desktop tests and Web tests together and can switch between two types of tests.

https://forum.katalon.com/t/is-this-possible-to-use-windows-desktop-testing-features-to-download-a-file-in-katalon/46317

**Comment by Padoplin** [comment]
This issue already has a workaround.
