### ISSUE TITLE
Using skipThisTestCase shows PASSED in junit test results instead of SKIPPED

### ISSUE THREAD

**Issue by natesthompson** [katalon-studio/katalon-studio#370]
https://forum.katalon.com/t/using-skipthistestcase-shows-passed-in-junit-test-results-instead-of-skipped/46387

#### Operating System: (for example: Windows 10 or OSX Sierra)
Ubuntu 18.04 LTS
#### Katalon Studio Version:
7.5.5

#### Katalon Studio logs:
When using this method: How to execute specific test cases from command line interface, to skip test cases we do not want to run based on some criteria, I see this called in the logs:
2020-08-12 21:48:21 - [TEST_STEP][PASSED] - testCaseContext.skipThisTestCase(): null
And result that katalon posts is test is skipped:
2020-08-12 21:48:21 - [MESSAGE][INFO] - Completed test case Test Cases/Acceptance Test/AboutSystem/LicensesInformationSpec with status SKIPPED
But on jenkins the junit xml that is parsed shows that the test is PASSED rather than SKIPPED.

#### Environment (for Mobile testing):

* Appium version - 1.16.1

* Mobile platform/version under test: Android 7

* Real device or emulator/simulator: Readl device

#### Actual Behavior: Using skipThisTestCase leads to PASSED being reported in junit report.

**Comment by Padoplin** [comment]
Hello @natesthompson 

We have added this ticket to our backlog. We will inform you when this bug is fixed.

Jass

**Comment by Padoplin** [comment]
Hello @natesthompson

This bug is fixed in version 7.8.1. Please upgrade!

Jass
