### ISSUE TITLE
Katalon studio cuts off object properties in window

### ISSUE THREAD

**Issue by natesthompson** [katalon-studio/katalon-studio#375]
See forum post here: https://forum.katalon.com/t/katalon-studio-cuts-off-object-properties-in-window/46177

**#### Operating System: (for example: Windows 10 or OSX Sierra)**
Windows 10

**#### Katalon Studio Version:**
7.6.2

**Appium version**
1.16

**Mobile platform/version under test: (for example: iOS 11 or Android 7)**
Android 7

**Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)**
Real device

**#### Steps to reproduce:**
Katalon studio obscures/cuts off object properties in window (thought this was fixed, but still present in 7.6.2) from a test object in Object Repository

**#### Expected Behavior:**
User should be able to scroll all the way down to bottom of "Object's Properties" window so they can modify all the object properties.

**#### Actual Behavior:**
User cannot scroll all the way down to bottom of "Object's Properties" window so they cannot modify all the object properties.

**#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)**
![image](https://user-images.githubusercontent.com/12702814/90823667-dbc4d500-e2fb-11ea-95c7-e70a75d8447f.png)

**Comment by Padoplin** [comment]
Hello @natesthompson 

This bug is fixed in version 7.8.1. Please upgrade!

Jass
