### ISSUE TITLE
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters inside docker

### ISSUE THREAD

**Issue by RamazanBiyik77** [katalon-studio/katalon-studio#377]
#### Katalon Studio logs:

* Docker(linux) logs folder: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/source/Test Suites/Booking-İzmir-Hotel-v2.groovy

#### Steps to reproduce:

Rename the test suit name with turkish character like : İ Ö ö Ü ü Ç ç Ğ ğ ı

I run my test with katalon studio. There was no error. Worked as expected. But when it comes to docker environment it failed with the error above. This problem is probably related with os based settings however i used official katalon docker image.
I think this is a bug that needs to be fixed inside dockerfile.
I tried to fix this wtih changing locale parameters with `export LANG="tr_TR.UTF-8"` but didn't work.
Do you know how can i fix that?

**Comment by duyluonganh** [comment]
@RamazanBiyik77 Please try this solution: https://stackoverflow.com/a/28406007/11269819

**Comment by RamazanBiyik77** [comment]
Thanks that solved my issue.
