### ISSUE TITLE
In Mac version test execution progress bar colour displaying BLUE colour when tests are failed 

### ISSUE THREAD

**Issue by hariprasadms** [katalon-studio/katalon-studio#38]
But in windows versiokn it works fine. 

![katalon-test-run-bar](https://user-images.githubusercontent.com/17435678/50253686-eae6d780-03e2-11e9-93eb-e32f693b60d0.png)

**Comment by devalex88** [comment]
This is a limitation of Eclipse RCP which Katalon Studio is currently built on top of.
