### ISSUE TITLE
Consistent tagging and numbering of pre-releases

### ISSUE THREAD

**Issue by mrowell** [katalon-studio/katalon-studio#383]
Releases on the GitHub releases page are not being tagged consistently.

Currently:
`v7.6.8.rc` is tagged as the latest release. If `v7.6.8` is a production release could it please be tagged without the `.rc`, if not it should be tagged as a pre-release
`v7.6.7` is tagged as pre-release
`v7.6.6` is tagged as a release
`v7.6.5`, `v7.6.4`, `v7.6.3` are tagged as pre-releases

Also currently the built in Check for Updates feature of Katalon Studio is downloading 7.6.6. 

This breaks our CI process that downloads the latest Katalon Engine release for our automated testing. 
The CI expects the latest release to be consistently versioned (ie without .rc) and that all pre-releases are tagged as pre-release.

Could all pre-releases be tagged as pre-releases?
Could all production releases have consistent version numbering and not include `.rc`?
Ideally, the latest GitHub release would also match the production release available in the Check for Updates feature of Katalon Studio.

Thanks,
Marcus.

**Comment by Padoplin** [comment]
Hello @mrowell 

We apologise for tagging releases inconsistently. We have noted the issue and will improve it. 

Thank you for letting us know!

Jass
