### ISSUE TITLE
Add support for test suite collection report display.

### ISSUE THREAD

**Issue by Fanlu91** [katalon-studio/katalon-studio#40]
The default report.html generated by katalon test suite execution integrates well with jenkins, both the HTML report and the JUnit one.
However it does not support export the test suite collection report (the xml format .pr file)  to other types(such as an index html) in console mode, it is really inconvenient that we eventually gave up to use suite collections in jenkins jobs. 
It will be great if a plugin can help to resolve this. Cheers.

**Comment by kungger888** [comment]
Have it solved?I just met the same question.

**Comment by devalex88** [comment]
Since 7.0.0 you can generate JUnit reports for Test Suite Collections in Katalon Studio Enterprise.
