### ISSUE TITLE
[Katalon 7.8.0] Error with message displayed in Console log with information "No application is started yet" after executing

### ISSUE THREAD

**Issue by locnguyen2020** [katalon-studio/katalon-studio#409]
After running a test case, test suite, test suite collection, observe the execution logs, there is error message displayed with information: "Caught: com.kms.katalon.core.exception.StepFailedException: No application is started yet.
com.kms.katalon.core.exception.StepFailedException: No application is started yet.
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.verifyWebDriverIsOpen(AppiumDriverManager.java:655)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.getDriver(AppiumDriverManager.java:630)"

Step:

1. Create new Sample Project of Web UI in Katalon tool
2. Run one test suite
3. After executing, go to Console tab

Actual result: Error message displayed and highlighted with red color
Expected result: No error messages displayed
![Screenshot_Bug2](https://user-images.githubusercontent.com/71815228/100331383-aae2f300-3002-11eb-8ced-0ed3ec8fc436.jpg)

**Comment by clifmo** [comment]
Following

**Comment by Padoplin** [comment]
Hello

This bug is fixed in version 7.8.2, which is available for upgrade.

Jass

**Comment by hari-bisen** [comment]
Hi Team I'm getting this Issue in version 7.9.1 any Comment? Thanks in advance.
