### ISSUE TITLE
BUG : Reports are getting overwritten while using this docker image

### ISSUE THREAD

**Issue by sunilaadike** [katalon-studio/katalon-studio#41]
![report_overwrite](https://user-images.githubusercontent.com/25978374/45873134-5652e600-bdaf-11e8-93ab-995f125b7170.png)

If a test suite collection has multiple suites, reports are getting overwritten when executing the test cases using docker run command. This is serious bug and this image can not be used until it gets fixed.

Issue is seen in both sequential and parallel execute of the test suite collection.

**Comment by devalex88** [comment]
I've moved this issue to https://github.com/katalon-studio/katalon-studio for planning.

**Comment by JICJ** [comment]
when running testsuits by command line ,reports are getting overwritten while having the same timestamp Is it comfirmed a bug ? and does you have any solutions ?@devalex88

**Comment by JICJ** [comment]
can we rename the reportFolder @devalex88

**Comment by jchatronLetsignit** [comment]
So the docker image can't fix this ? we have to wait for the katalon main project to fix it ?

**Comment by isurunix** [comment]
I'm facing the same issue on the standalone version in console mode. Any idea when this is going to be fixed?

**Comment by jchatronLetsignit** [comment]
Any update on this ?

**Comment by jeroengijsman** [comment]
also having this issue, i just created a new issue in the docker repo https://github.com/katalon-studio/docker-images/issues/46.

**Comment by aditki** [comment]
@jchatronLetsignit Tried that and the JUnit_report.xml is not generated when the listener is called. Any work around for this?

**Comment by devalex88** [comment]
Thank you for your report. Please follow katalon-studio/katalon-studio#19. This issue has been planned to be fixed in 6.1.0.

**Comment by jchatronLetsignit** [comment]
Nice thanks for your work !
