### ISSUE TITLE
ConsoleMain_MSG_DEVOPS_LICENSE_COMPATIBILITY 

### ISSUE THREAD

**Issue by clifmo** [katalon-studio/katalon-studio#425]
I need an immediate answer as to what causes this error and how to remove it.

Warning: NLS missing message: ConsoleMain_MSG_DEVOPS_LICENSE_COMPATIBILITY in: com.kms.katalon.execution.constants.executionMessages

- Katalon Studio Version: 7.8.2
- OS Version: win10
- Browser Version: chrome (not related to issue)

Steps to Reproduce:

1. Run a test with TestOps integration enabled

Expected behavior: 
1. Upload results to TestOps

Screenshots: not applicable

**Comment by duyluonganh** [comment]
Hi @clifmo,

The message: "Warning: NLS missing message: ConsoleMain_MSG_DEVOPS_LICENSE_COMPATIBILITY in: com.kms.katalon.execution.constants.executionMessages" is just an unnecessary warning message that also doesn't harm your test.

If your tests did not upload to TestOps, please help to the console log as a text file.

**Comment by MPParsley** [comment]
The message might be unnecessary but it causes Travis to fail due to an exit code=1. See https://github.com/katalon-studio/docker-images/issues/103
