### ISSUE TITLE
Bug : In pixman_region32_init_rect

### ISSUE THREAD

**Issue by nerosha09** [katalon-studio/katalon-studio#43]
#### Katalon Studio logs:

I didnot find anything like that

#### Environment (for Web testing):

Browser and Browser version

Chrome and Firefox

#### Steps to reproduce:

Please also provide your test scripts if possible.

#### Actual Behavior:
 BUG
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Cannot save the Test case
I opened Katalon studio successfully in console mode in ubuntu 16.04...The katalon studio is able to record but when saving the testcase i am getting an error called " BUG
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug"
and it is still showing in progress..In my eclipse.ini file the launcher is in GTK 2 version only...Can you please help me with this.And Thanks in advance

#### Screenshots / Videos:
![issue](https://user-images.githubusercontent.com/34099504/50950902-6f53e400-14d1-11e9-817b-1e94fbd7d52f.png)

**Comment by Padoplin** [comment]
Hi @nerosha09,

I hope you’ve had a great experience with Katalon Studio. Regarding your issue, I’m glad to let you know we’ve already fixed it in Katalon Studio version 6.2.2. Please download the latest version at https://www.katalon.com/ or check for updates.

Thank you so much for your contribution.

Jass
