### ISSUE TITLE
Connection is not secure Issue in chrome browser while executing testcases in emulator

### ISSUE THREAD

**Issue by PriyankaKeer** [katalon-studio/katalon-studio#450]
#### Environment (for Mobile testing):

* Appium version--1.20.2

* Mobile platform/version under test: (for example: iOS 11 or Android 7) -- Android 11.0

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator) --Android Emulator Pixel_3_XL_API_30

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)--NA

* Appium Logs: <Project folder>\.appium--NA

* Application file (.apk/.ipa): (if possible) ---NA

#### Steps to reproduce:

Record a testcase in katalon, and execute the testcase from android emulator.

Connection is not secure issue in chrome (while navigating to URL) when trying to execute responsive mobile app testcases

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
![ConnectionIssue](https://user-images.githubusercontent.com/71713278/108700853-351cf380-752d-11eb-9fd8-f678b6ab31df.PNG)

**Comment by duyluonganh** [comment]
Hi @PriyankaKeer,

Please enable wifi or cellular data on your phone then run again.
