### ISSUE TITLE
Katalon fails to generate Junit.xml report due to execution log having extra </log>

### ISSUE THREAD

**Issue by natesthompson** [katalon-studio/katalon-studio#455]
**#### Operating System: (for example: Windows 10 or OSX Sierra)**
Ubuntu 16.04.7 LTS
**#### Katalon Studio Version:**
7.8.2
**#### Katalon Studio logs:**
see bottom
**#### Environment (for Mobile testing):**
Appium version 1.18.1
Android 9 device
#### Steps to reproduce:
This comes up infrequently, Katalon sometimes adds an extra “<//log>” to the execution0.log for a test suite, resulting in JUnit.xml report not generating because the xml is invalid. This was observed while running tests with KRE.

#### Expected Behavior:
JUnit xml report to be generated, valid execution0.log file
![image](https://user-images.githubusercontent.com/12702814/110014464-70b37c80-7ce8-11eb-8804-2b6b2373dcd2.png)

#### Actual Behavior:
JUnit xml report fails to generate due to invalid execution0.log file with extra "<//log>" in it.
![image](https://user-images.githubusercontent.com/12702814/110013888-c5a2c300-7ce7-11eb-9e14-eb36775e95ca.png)

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
11:33:19 2021-03-04 17:33:21 INFO Class: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2864,9]
11:33:19 2021-03-04 17:33:21 INFO Class: Message: The markup in the document following the root element must be well-formed.
11:33:19 2021-03-04 17:33:21 INFO Class: at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.core.logging.TestSuiteXMLLogParser.processFile(TestSuiteXMLLogParser.java:85)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.core.logging.TestSuiteXMLLogParser.readTestSuiteLogFromXMLFiles(TestSuiteXMLLogParser.java:62)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.core.reporting.ReportUtil.generate(ReportUtil.java:453)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.core.reporting.ReportUtil.generate(ReportUtil.java:463)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.execution.launcher.ReportableLauncher.prepareReport(ReportableLauncher.java:353)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.execution.launcher.ReportableLauncher.preExecutionComplete(ReportableLauncher.java:144)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.execution.launcher.ProcessLauncher.onWatchdogComplete(ProcessLauncher.java:192)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.execution.launcher.LaunchWatchdog.notifyProcessTerminated(LaunchWatchdog.java:136)
11:33:19 2021-03-04 17:33:21 INFO Class: at com.kms.katalon.execution.launcher.LaunchWatchdog.run(LaunchWatchdog.java:66)
11:33:19 2021-03-04 17:33:21 INFO Class: at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/12702814/110013888-c5a2c300-7ce7-11eb-9e14-eb36775e95ca.png)

**Comment by duyluonganh** [comment]
Hi @natesthompson,

This issue has been fixed in [v8.0.5](https://docs.katalon.com/katalon-studio/new/version-8x.html#official-release---version-805). Please Check for Update.
