### ISSUE TITLE
Not able to add the value with multiple lines in the variable section (Global or Normal)

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#46]
https://katalon.zendesk.com/agent/tickets/120

We came across an issue where when we add a value having multiple lines like a JSON value, the variable section in GLOBAL variable or in the API variable section, does not includes the new line values.

I am using the below value, which i want to give a variable value: 
"CustomFields" : [ 
{ 
"name" : "ProposedContractAmount1", 
"type" : "java.lang.Integer", 
"value" : "0" 
}, 
When give and check, it only takes "CustomFields" : [ and not the full value.

**Comment by longngbui** [comment]
Fixed
