### ISSUE TITLE
[Bug] Katalon throws error "Cannot generate test steps" for custom script tests

### ISSUE THREAD

**Issue by AcharyaKavya** [katalon-studio/katalon-studio#488]
- Katalon Studio Version: 8.0.5
- OS Version: 92.0.4515
- Browser Version: Chrome

Steps to Reproduce:

1. Open any Katalon test with custom steps (manually added steps that are not generated by Katalon)
2. Click on Record Web icon

Please find attached **Error log file** content for your reference: 
[Katalon_ErrorLog.txt](https://github.com/katalon-studio/katalon-testops/files/6938046/Katalon_ErrorLog.txt)

**Expected behavior:** Pop Up window with message "Do you want to continue recording test case: 'XYZ'" should appear

Screenshots: 

![Screenshot 2021-08-05 at 12 53 32](https://user-images.githubusercontent.com/25530236/128338728-399b99c4-d7a9-4572-8489-250e0998ef0c.png)

**Actual behavior:** Error message "Cannot generate test steps" is shown

Screenshot: 

![Screenshot 2021-08-05 at 12 37 39](https://user-images.githubusercontent.com/25530236/128338935-5b1c30fa-a09a-41c5-9407-a7b0181af024.png)

**Comment by AcharyaKavya** [comment]
@nhpthuy Thanks for your reply

**Comment by nhpthuy** [comment]
Hi @AcharyaKavyam

This issue was fixed in version 8.1.0. You can download the latest version [here](https://www.katalon.com/download/) and see [Release Notes](https://docs.katalon.com/katalon-studio/new/version-8x.html) for more details.

Regards, 
Shin

**Comment by AcharyaKavya** [comment]
Hi @nhpthuy,

Thanks for your reply.

This issue still occurs on Mac OS and is mentioned in https://support.katalon.com/hc/en-us/requests/5304.

Regards,
Kavya
