### ISSUE TITLE
I cant call two same test cases in 1 test suite

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#49]
https://katalon.zendesk.com/agent/tickets/129

I currently add duplicated test cases to a test suite and using data binding for both of test cases. However, when I click Run the test suite, error thrown to inform me that the test suite is invalide

Steps:

Add duplicated test cases A into a test suite
Bind data for test case A and its duplicated one
Click Run button
Expeced result: Test suite is run successfully

Actual result: An error thrown about invalid test suite (see attachment)

**Comment by nani5384** [comment]
![image](https://user-images.githubusercontent.com/18727214/51415533-c003b680-1b3b-11e9-9350-0b3ba08c05bc.png)
 
Similar issue, running Registration test, login test, upload test and again login test.......Issue is login test response is not getting updated from upload test run in a test suite. But, if I run login test seperately after upload test response is getting updated.

**Comment by dungleonhart** [comment]
Issue code: KAT-4017

**Comment by longngbui** [comment]
Fixed in v6.0.4
