### ISSUE TITLE
Trying to use global variable in URL field of POST object 

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#50]
https://katalon.zendesk.com/agent/tickets/110

A bility to use GlobalVariable directly in KS.

**Comment by Padoplin** [comment]
Hi @trongbui,

Thanks a lot for your feedback. Starting with version 6.3.0 (beta), Katalon Studio supports directly parameterizing Global variables in Test Objects. 

Enjoy testing.

Padoplin.
