### ISSUE TITLE
Not able to set proxy settings to selenium grid for accessing applications behind firewall 

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#51]
https://katalon.zendesk.com/agent/tickets/121

We are currently trying to use Katalon with Selenium Grid to connect to an application behind the firewall. Currently it's not supported to send the proxy information to remote browser.

This is issue is same as what is explained in below thread.

https://forum.katalon.com/t/katalon-studio-behind-proxy-is-unable-to-open-browser-on-browserstack/10036/12

Our infrastructure is in microsoft Azure (Grid and Katalon executor) and our application is behind a firewall. We should be setting the proxy as part of desired capabilities of the driver instance but currently there is no way to set it.

Looks like it's still an issue as per above thread , could you please look into it?

**Comment by SriharshaTV** [comment]
any documentation on how to do this setting ?

**Comment by SriharshaTV** [comment]
Got the settings from Oliver that it uses the proxy settings from preferences. However this is not working for us. Can some one help in this regard ?

**Comment by devalex88** [comment]
Please test again with [Katalon Studio 6.0.6 beta](https://forum.katalon.com/t/updated-mar-8th-beta-release-6-0-6/20561) and let us know the result.

**Comment by devalex88** [comment]
Related issue: passing proxy information to the selenium grid to connect to application behind firewall #20.

**Comment by devintest** [comment]
Hi, This is still not fixed with version 6.0.6, I am unable to run tests on browserstack behind proxy. Please can you check this.

Regards, 
Krishna

**Comment by devintest** [comment]
Please can you look into this issue. 

Regards, 
Krishna

**Comment by SriharshaTV** [comment]
In 6.0.6 we are able.to access the application behind firewall.

**Comment by devintest** [comment]
Tested again, proxy issue is fixed on 6.0.6 version.
