### ISSUE TITLE
Custom Keyword Issue when running from Bamboo

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#55]
https://katalon.zendesk.com/agent/tickets/101

I am seeing issue when executing customKeyword from Bamboo and I am not getting issue while running locally. I actually moved the custom Keyword from one package to another and I update the path in the Script View. My team members were also facing the same issue and they advised me to do it from the Manual view and select the custom keyword from the drop-down. I did that step but still it is not working for me. So i created the keyword with new name and package and pushed it with the new compiled class but still i am getting the issue java.lang.ClassNotFoundException: customWeb.webUtil. Please advise and let me know if you require any more information. PFA attached generated Report and commit file.

I found this thread and he is having issue in Jenkins. So i believe the issue is not just tied to Bamboo? 
https://stackoverflow.com/questions/53776207/updated-katalon-studio-to-version-5-9-1-classnotfoundexception

**Comment by trongbui** [comment]
Any updates on this issue? We are also starting new project with API testing and in our current project we are doing workaround but i believe as the Reusable Test Case grow we will have to convert all of them to custom keyword and that will increase our overhead time to again convert and Test all those keywords. So i guess at this point we can say that it is turning out to be an impediment with not having this issue resolved sooner.

**Comment by duyluonganh** [comment]
@trongbui please ask him install Java OpenJDK 1.8

**Comment by duyluonganh** [comment]
sudo apt-get install openjdk-8-jre
sudo update-alternatives --config java //then choose the openjdk-8-jre option
java -version
