### ISSUE TITLE
Katalon Suite, huge memory issue

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#56]
https://katalon.zendesk.com/agent/tickets/111

Katalon grows to over 4 Gig of memory with over 60 variables defined in a test case. these would then get mapped to the corresponding columns in a spreadsheet. we do this for automated testing. it basically grinds my pc to a halt. i have shut down as much as i can to run Katalon, including the spreadsheet, windows explorer, any browser, mail programs, etc etc, even notepad lite. i shut down skype, windows Word, you name it to free up memory. My new notebook grinds to a halt just adding 1 variable and moving it up the list of variables to near the top. i have attached a screen snapshot of the memory. it says 65-69% but this is wrong. it is swapping out memory to run Katalon.

**Comment by ssheetal** [comment]
Is this issue fixed? I am seeing problems related to garbage collection resulting in OutOfMemory error(s) as below. Is there any limit on the lines of code/test variables to be defined?

An internal error occurred during: "Git Repository Change Scanner".
GC overhead limit exceeded
An internal error occurred during: "Requesting Java AST from selection".
GC overhead limit exceeded

**Comment by devalex88** [comment]
@ssheetal Thank you for the report. The original issue has been fixed. For your issue please provide detailed information at https://forum.katalon.com so that we can resolve it for you. If possible you can send your project source code to info@katalon.com to help us reproduce the issue.
