### ISSUE TITLE
Unable to take screenshot on Safari when the video is playing

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#57]
https://katalon.zendesk.com/agent/tickets/88

Attached the test case. I use youtube as an example website. When I take screenshot for the safari video player, the image is all black. I have tested in Chrome and Firefox, seems this case only happen in safari. My safari version is 12.0.1

**Comment by dungleonhart** [comment]
This is a limitation of Safari. Cannot fix.
