### ISSUE TITLE
Ability to set default execution profile on a project level

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#60]
https://forum.katalon.com/t/profiles-set-up-defaultprofile/17838/2

I want to set default profile execution to the profile I want (not "Default" one) on a project scope.

**Comment by BloodyMettle** [comment]
+1 for this. 

Also renaming the default profile or be able to delete it would be nice As long as there is one profile it should be fine - if someone deletes all profiles, the default file can be generated on build. There's not a lot of information in there anyways.

This would require to get rid of the hardcoded dependency on a profile name "default" in the generated `GlobalVariables` class

```
static {
        try {
            def selectedVariables = TestCaseMain.getGlobalVariables("default") //... why? 
			selectedVariables += TestCaseMain.getGlobalVariables(RunConfiguration.getExecutionProfile())
            selectedVariables += RunConfiguration.getOverridingParameters()
        } catch (Exception e) {
            TestCaseMain.logGlobalVariableError(e)
        }
}
```

**Comment by Padoplin** [comment]
Hi there

Katalon Studio allows setting a default execution profile at project level in version 7.4.2. 

You can download version 7.4.2 [here](https://github.com/katalon-studio/katalon-studio/releases/v7.4.2) and [learn more about how to do that](https://docs.katalon.com/katalon-studio/docs/execution-profile-v54.html#set-default-profile-at-project-level).

Jass
