### ISSUE TITLE
Support overriding global variable for test suite collections

### ISSUE THREAD

**Issue by dungleonhart** [katalon-studio/katalon-studio#61]
Original post: https://forum.katalon.com/t/katalon-studio-5-10-beta-release/15344/15

**Comment by dungleonhart** [comment]
Issue code: KAT-4045

**Comment by kazurayam** [comment]
Not yet fixed in v6.1.2
https://forum.katalon.com/t/override-profile-variables-doesnt-work-for-test-suite-collections/18114/3
