### ISSUE TITLE
[Windows 7] Issue Faced during Recording the script in Katalon Studio

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#72]
https://katalon.zendesk.com/agent/tickets/161

We are facing the below issue while Recording the script in Katalon Studio:

1. While recording a complete flow of a web application , only 'Open Browser' and 'Close Browser' steps are getting recorded skipping all other actions. 
2. Also, using Object Spy does not recognize the objects and thus this feature does not help us in identifying the object locators. 

This issue is faced with every URL we use i.e even if we try to use the google URL as shown in the below screenshot. 
Katalon Studio Version - 5.10.0 
Even we tried installing the lower versions of Katalon Studio but nothing helped. 
Browser Used - Chrome 
Browser Version - 71.0.3578

**Comment by trongbui** [comment]
Sure please. 
We dont have access to GitHub Url's, so it would be great if your team can keep us posted through the mail about the status of ticket you raised.

**Comment by duyluonganh** [comment]
The client has confirmed that it was a client's system issue, so we can close this now @trongbui.
