### ISSUE TITLE
Cannot open project having too many GlobalVariables

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#74]
https://katalon.zendesk.com/agent/tickets/182

- Create a Profile having ~ 250 variables
- Open scripting mode and copy its XML content
- Create another profile with this XML content

Issue 1:
 - New profile's variables cannot be understood by Katalon Studio

Issue 2:
- Reopen the project causing an exception on building the profile

**Comment by longngbui** [comment]
Fixed in 6.1.0
