### ISSUE TITLE
CallTestCase using in try-catch block throws StepFailedException

### ISSUE THREAD

**Issue by duyluonganh** [katalon-studio/katalon-studio#79]
Expected result:
If users use callTestCase in `try-catch` block, KS should NOT throw StepFailedException. Main Test Case should pass if nothing throws in the `catch` or `finally` block.
Actual result
If users use callTestCase in `try-catch` block, KS throws StepFailedException and marks the main test case failed.

Related issues in forum:
https://forum.katalon.com/t/how-to-stop-test-case-in-catch-block/18291
https://forum.katalon.com/t/try-catch-report-issue-in-katalon/9251

**Comment by kazurayam** [comment]
please have a look at my post:
https://forum.katalon.com/t/fail-a-privitive-keyword-reproducing-problem-of-try-catch-in-test-case/18369

**Comment by NgocTMPhan** [comment]
issue code: KAT-4095

**Comment by duyluonganh** [comment]
Fixed in 6.0.5
