### ISSUE TITLE
Call a test case several times in a test suite

### ISSUE THREAD

**Issue by dungleonhart** [katalon-studio/katalon-studio#8]
Issue code: KAT-2981
Originally posted at https://forum.katalon.com/discussion/5116 by Thibaud A

> I'm working with Katalon and I'd like to call a test case several times.
> For example I make a login test case which try to log in with variables we previously set in other test case.
> 
> I already find two ways to do it but I don't find them clean :
> - the first one consist on modify the .ts file that correspond to my test suite
> - the second is to use the function WebUI.callTestCase in my test case and use a test case as a test suite.

**Comment by dungleonhart** [comment]
This feature has been implemented in Katalon Studio 5.9

**Comment by gburch** [comment]
There is a bug when you have a test case multiple times and have different binding for ScriptVariable. It will always just take the data from the first instance of the test case.
