### ISSUE TITLE
Katalon Studio crash on launch

### ISSUE THREAD

**Issue by sreejithbnaick** [katalon-studio/katalon-studio#92]
#### Katalon Studio logs: Attached, please find it

[katalon-crash.txt](https://github.com/katalon-studio/katalon-studio/files/2847853/katalon-crash.txt)
[hs_err_pid9676.log](https://github.com/katalon-studio/katalon-studio/files/2847855/hs_err_pid9676.log)

**Comment by duyluonganh** [comment]
@sreejithbnaick Could you please attach Katalon Log files /config/.metadata/.log and specify your system information: CPU, RAM

**Comment by sreejithbnaick** [comment]
![hwinfo](https://user-images.githubusercontent.com/4578153/52652686-95c3cf80-2f14-11e9-8c41-44ab0cc9770b.png)
[metadata.log](https://github.com/katalon-studio/katalon-studio/files/2856749/metadata.log)

**Comment by sreejithbnaick** [comment]
![osinfo](https://user-images.githubusercontent.com/4578153/52653228-95780400-2f15-11e9-89ba-12e806f74ee4.png)

**Comment by duyluonganh** [comment]
@sreejithbnaick This bug is a known issue of eclipse https://bugs.eclipse.org/bugs/show_bug.cgi?id=497705, please install gtk3.0 to resolve

**Comment by sreejithbnaick** [comment]
![gtk](https://user-images.githubusercontent.com/4578153/53685912-f3df1800-3d46-11e9-99ee-e51e4152e535.png)

Already have gtk3. Any way, I will go through the bug link you have shared for workaround. Thanks

**Comment by sreejithbnaick** [comment]
I found workaround from the bug link, and it is working
As mentioned in https://bugs.eclipse.org/bugs/show_bug.cgi?id=497705#c7

```
export SWT_WEBKIT2=1
export SWT_GTK3=0
```

**Comment by duyluonganh** [comment]
Great! Thank @sreejithbnaick

**Comment by vherasme** [comment]
> I found workaround from the bug link, and it is working
> As mentioned in https://bugs.eclipse.org/bugs/show_bug.cgi?id=497705#c7
> 
> ```
> export SWT_WEBKIT2=1
> export SWT_GTK3=0
> ```

Hi. How an I supposed to put this in practice. I don't know where to use those paramerters.

**Comment by duyluonganh** [comment]
@vherasme Please put this in `~/.bashrc` file. After the edit, use
```sh
source ~/.bashrc
```
to load the environment variables then reopen Katalon Studio
