### ISSUE TITLE
Ability to open, read, edit and save arbitrary text files in Katalon Studio

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#94]
As an advanced user, I want to be able to open, read, edit and save text files such as Readme.md or .gitignore.

https://forum.katalon.com/t/eclipse-project-explorer-tab-in-katalon-studio/19116

**Comment by kazurayam** [comment]
Ability to open and read text is not enough. I want to edit and save it.

**Comment by minhthanh3145** [comment]
@kazurayam 
Edited !

**Comment by devalex88** [comment]
This feature is available in the current version of Katalon Studio.
