### ISSUE TITLE
Error when adding more than one variable on Rest URL

### ISSUE THREAD

**Issue by kelson-pereira** [katalon-studio/katalon-studio#95]
#### Katalon Studio Version: 5.10.1

Error when adding more than one **variable** like `${var_1}:${var_2}` on **Rest URL** at Web Service Request object repository.

#### Steps to reproduce:
I'm working on API Rest tests using Katalon Studio.

I created a Web Service Request object in Object Repository.

In the Variables tab I include three local variables with reference to global variables each.

In the Request Restore URL I include two local variables.

After completing the requisition configuration, I saved the project.

#### Expected Behavior:
The variables should be recognized and accepted by the interface when they are saved.

#### Actual Behavior:
Test Katalon Studio show an empty error message when saving project after changes.

![2019-02-11 12_34_51-recordingstatusform](https://user-images.githubusercontent.com/47066976/52570046-6fb20880-2e0a-11e9-8080-d3463fb53984.png)

**Comment by NgocTMPhan** [comment]
@kelson-pereira Thanks for your information, the issue similar in my side. This issue has been logged and it will be fixed in the next version. In meanwhile, you can use the standard of URL instead of using two variable on URL. 
** Issue code: 4118

**Comment by kelson-pereira** [comment]
@NgocTMPhan, thank you for addressing this issue.

Have a great day!

Regards,

**Comment by NgocTMPhan** [comment]
@kelson-pereira, bad news for you it didn't persist with latest versions,  please use the new version of Katalon Studio at link below, and let us know the result
https://katalon.s3.amazonaws.com/release-beta/6.1.1.rc5/Katalon%20Studio.app.zip
https://katalon.s3.amazonaws.com/release-beta/6.1.1.rc5/Katalon%20Studio.dmg 1
https://katalon.s3.amazonaws.com/release-beta/6.1.1.rc5/Katalon_Studio_Linux_64-6.1.1.rc5.tar.gz
https://katalon.s3.amazonaws.com/release-beta/6.1.1.rc5/Katalon_Studio_Windows_32-6.1.1.rc5.zip
https://katalon.s3.amazonaws.com/release-beta/6.1.1.rc5/Katalon_Studio_Windows_64-6.1.1.rc5.zip
